// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/OJOMB/fightpicker/pkg/clients/postgres"
	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgtype"
	mock "github.com/stretchr/testify/mock"
)

// NewMockClient creates a new instance of MockClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockClient {
	mock := &MockClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockClient is an autogenerated mock type for the Client type
type MockClient struct {
	mock.Mock
}

type MockClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockClient) EXPECT() *MockClient_Expecter {
	return &MockClient_Expecter{mock: &_m.Mock}
}

// CreateUser provides a mock function for the type MockClient
func (_mock *MockClient) CreateUser(ctx context.Context, arg postgres.CreateUserParams) error {
	ret := _mock.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for CreateUser")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, postgres.CreateUserParams) error); ok {
		r0 = returnFunc(ctx, arg)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockClient_CreateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateUser'
type MockClient_CreateUser_Call struct {
	*mock.Call
}

// CreateUser is a helper method to define mock.On call
//   - ctx context.Context
//   - arg postgres.CreateUserParams
func (_e *MockClient_Expecter) CreateUser(ctx interface{}, arg interface{}) *MockClient_CreateUser_Call {
	return &MockClient_CreateUser_Call{Call: _e.mock.On("CreateUser", ctx, arg)}
}

func (_c *MockClient_CreateUser_Call) Run(run func(ctx context.Context, arg postgres.CreateUserParams)) *MockClient_CreateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 postgres.CreateUserParams
		if args[1] != nil {
			arg1 = args[1].(postgres.CreateUserParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockClient_CreateUser_Call) Return(err error) *MockClient_CreateUser_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockClient_CreateUser_Call) RunAndReturn(run func(ctx context.Context, arg postgres.CreateUserParams) error) *MockClient_CreateUser_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteUserByID provides a mock function for the type MockClient
func (_mock *MockClient) DeleteUserByID(ctx context.Context, id pgtype.UUID) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteUserByID")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, pgtype.UUID) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockClient_DeleteUserByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteUserByID'
type MockClient_DeleteUserByID_Call struct {
	*mock.Call
}

// DeleteUserByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id pgtype.UUID
func (_e *MockClient_Expecter) DeleteUserByID(ctx interface{}, id interface{}) *MockClient_DeleteUserByID_Call {
	return &MockClient_DeleteUserByID_Call{Call: _e.mock.On("DeleteUserByID", ctx, id)}
}

func (_c *MockClient_DeleteUserByID_Call) Run(run func(ctx context.Context, id pgtype.UUID)) *MockClient_DeleteUserByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 pgtype.UUID
		if args[1] != nil {
			arg1 = args[1].(pgtype.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockClient_DeleteUserByID_Call) Return(err error) *MockClient_DeleteUserByID_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockClient_DeleteUserByID_Call) RunAndReturn(run func(ctx context.Context, id pgtype.UUID) error) *MockClient_DeleteUserByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserByID provides a mock function for the type MockClient
func (_mock *MockClient) GetUserByID(ctx context.Context, id pgtype.UUID) (postgres.GetUserByIDRow, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetUserByID")
	}

	var r0 postgres.GetUserByIDRow
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, pgtype.UUID) (postgres.GetUserByIDRow, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, pgtype.UUID) postgres.GetUserByIDRow); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(postgres.GetUserByIDRow)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, pgtype.UUID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClient_GetUserByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserByID'
type MockClient_GetUserByID_Call struct {
	*mock.Call
}

// GetUserByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id pgtype.UUID
func (_e *MockClient_Expecter) GetUserByID(ctx interface{}, id interface{}) *MockClient_GetUserByID_Call {
	return &MockClient_GetUserByID_Call{Call: _e.mock.On("GetUserByID", ctx, id)}
}

func (_c *MockClient_GetUserByID_Call) Run(run func(ctx context.Context, id pgtype.UUID)) *MockClient_GetUserByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 pgtype.UUID
		if args[1] != nil {
			arg1 = args[1].(pgtype.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockClient_GetUserByID_Call) Return(getUserByIDRow postgres.GetUserByIDRow, err error) *MockClient_GetUserByID_Call {
	_c.Call.Return(getUserByIDRow, err)
	return _c
}

func (_c *MockClient_GetUserByID_Call) RunAndReturn(run func(ctx context.Context, id pgtype.UUID) (postgres.GetUserByIDRow, error)) *MockClient_GetUserByID_Call {
	_c.Call.Return(run)
	return _c
}

// ListUsers provides a mock function for the type MockClient
func (_mock *MockClient) ListUsers(ctx context.Context, arg postgres.ListUsersParams) ([]postgres.ListUsersRow, error) {
	ret := _mock.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for ListUsers")
	}

	var r0 []postgres.ListUsersRow
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, postgres.ListUsersParams) ([]postgres.ListUsersRow, error)); ok {
		return returnFunc(ctx, arg)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, postgres.ListUsersParams) []postgres.ListUsersRow); ok {
		r0 = returnFunc(ctx, arg)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]postgres.ListUsersRow)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, postgres.ListUsersParams) error); ok {
		r1 = returnFunc(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockClient_ListUsers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListUsers'
type MockClient_ListUsers_Call struct {
	*mock.Call
}

// ListUsers is a helper method to define mock.On call
//   - ctx context.Context
//   - arg postgres.ListUsersParams
func (_e *MockClient_Expecter) ListUsers(ctx interface{}, arg interface{}) *MockClient_ListUsers_Call {
	return &MockClient_ListUsers_Call{Call: _e.mock.On("ListUsers", ctx, arg)}
}

func (_c *MockClient_ListUsers_Call) Run(run func(ctx context.Context, arg postgres.ListUsersParams)) *MockClient_ListUsers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 postgres.ListUsersParams
		if args[1] != nil {
			arg1 = args[1].(postgres.ListUsersParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockClient_ListUsers_Call) Return(listUsersRows []postgres.ListUsersRow, err error) *MockClient_ListUsers_Call {
	_c.Call.Return(listUsersRows, err)
	return _c
}

func (_c *MockClient_ListUsers_Call) RunAndReturn(run func(ctx context.Context, arg postgres.ListUsersParams) ([]postgres.ListUsersRow, error)) *MockClient_ListUsers_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateUserByID provides a mock function for the type MockClient
func (_mock *MockClient) UpdateUserByID(ctx context.Context, arg postgres.UpdateUserByIDParams) error {
	ret := _mock.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for UpdateUserByID")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, postgres.UpdateUserByIDParams) error); ok {
		r0 = returnFunc(ctx, arg)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockClient_UpdateUserByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateUserByID'
type MockClient_UpdateUserByID_Call struct {
	*mock.Call
}

// UpdateUserByID is a helper method to define mock.On call
//   - ctx context.Context
//   - arg postgres.UpdateUserByIDParams
func (_e *MockClient_Expecter) UpdateUserByID(ctx interface{}, arg interface{}) *MockClient_UpdateUserByID_Call {
	return &MockClient_UpdateUserByID_Call{Call: _e.mock.On("UpdateUserByID", ctx, arg)}
}

func (_c *MockClient_UpdateUserByID_Call) Run(run func(ctx context.Context, arg postgres.UpdateUserByIDParams)) *MockClient_UpdateUserByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 postgres.UpdateUserByIDParams
		if args[1] != nil {
			arg1 = args[1].(postgres.UpdateUserByIDParams)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockClient_UpdateUserByID_Call) Return(err error) *MockClient_UpdateUserByID_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockClient_UpdateUserByID_Call) RunAndReturn(run func(ctx context.Context, arg postgres.UpdateUserByIDParams) error) *MockClient_UpdateUserByID_Call {
	_c.Call.Return(run)
	return _c
}

// WithTx provides a mock function for the type MockClient
func (_mock *MockClient) WithTx(tx pgx.Tx) *postgres.Queries {
	ret := _mock.Called(tx)

	if len(ret) == 0 {
		panic("no return value specified for WithTx")
	}

	var r0 *postgres.Queries
	if returnFunc, ok := ret.Get(0).(func(pgx.Tx) *postgres.Queries); ok {
		r0 = returnFunc(tx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*postgres.Queries)
		}
	}
	return r0
}

// MockClient_WithTx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WithTx'
type MockClient_WithTx_Call struct {
	*mock.Call
}

// WithTx is a helper method to define mock.On call
//   - tx pgx.Tx
func (_e *MockClient_Expecter) WithTx(tx interface{}) *MockClient_WithTx_Call {
	return &MockClient_WithTx_Call{Call: _e.mock.On("WithTx", tx)}
}

func (_c *MockClient_WithTx_Call) Run(run func(tx pgx.Tx)) *MockClient_WithTx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 pgx.Tx
		if args[0] != nil {
			arg0 = args[0].(pgx.Tx)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockClient_WithTx_Call) Return(queries *postgres.Queries) *MockClient_WithTx_Call {
	_c.Call.Return(queries)
	return _c
}

func (_c *MockClient_WithTx_Call) RunAndReturn(run func(tx pgx.Tx) *postgres.Queries) *MockClient_WithTx_Call {
	_c.Call.Return(run)
	return _c
}
