all: false
# Use a non-templated path for the base directory, 
# or a different variable like {{.InterfaceDir}} if available at top level.
# A common pattern is to keep `dir` simple and use a more specific
# variable inside the package config.
dir: test/mocks
filename: '{{.InterfaceName}}_mock.go'
force-file-write: true
formatter: goimports
log-level: info
structname: '{{.Mock}}{{.InterfaceName}}'
pkgname: mocks
recursive: false
template: testify

packages:
  github.com/OJOMB/fightpicker/internal/server/handlers/v1/users:
    config:
      dir: test/mocks/{{.SrcPackageName}} 
    interfaces:
      Service:
  github.com/OJOMB/fightpicker/internal/repo/users:
    config:
      dir: test/mocks/{{.SrcPackageName}}
    interfaces:
      Client:
  github.com/OJOMB/fightpicker/pkg/logger:
    config:
      dir: test/mocks/{{.SrcPackageName}}
    interfaces:
      Logger: