// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/OJOMB/fightpicker/pkg/logs"
	mock "github.com/stretchr/testify/mock"
)

// NewMockLogger creates a new instance of MockLogger. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockLogger(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockLogger {
	mock := &MockLogger{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockLogger is an autogenerated mock type for the Logger type
type MockLogger struct {
	mock.Mock
}

type MockLogger_Expecter struct {
	mock *mock.Mock
}

func (_m *MockLogger) EXPECT() *MockLogger_Expecter {
	return &MockLogger_Expecter{mock: &_m.Mock}
}

// DebugContext provides a mock function for the type MockLogger
func (_mock *MockLogger) DebugContext(ctx context.Context, msg string, args ...any) {
	if len(args) > 0 {
		_mock.Called(ctx, msg, args)
	} else {
		_mock.Called(ctx, msg)
	}

	return
}

// MockLogger_DebugContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DebugContext'
type MockLogger_DebugContext_Call struct {
	*mock.Call
}

// DebugContext is a helper method to define mock.On call
//   - ctx context.Context
//   - msg string
//   - args ...any
func (_e *MockLogger_Expecter) DebugContext(ctx interface{}, msg interface{}, args ...interface{}) *MockLogger_DebugContext_Call {
	return &MockLogger_DebugContext_Call{Call: _e.mock.On("DebugContext",
		append([]interface{}{ctx, msg}, args...)...)}
}

func (_c *MockLogger_DebugContext_Call) Run(run func(ctx context.Context, msg string, args ...any)) *MockLogger_DebugContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []any
		var variadicArgs []any
		if len(args) > 2 {
			variadicArgs = args[2].([]any)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockLogger_DebugContext_Call) Return() *MockLogger_DebugContext_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockLogger_DebugContext_Call) RunAndReturn(run func(ctx context.Context, msg string, args ...any)) *MockLogger_DebugContext_Call {
	_c.Run(run)
	return _c
}

// ErrorContext provides a mock function for the type MockLogger
func (_mock *MockLogger) ErrorContext(ctx context.Context, msg string, args ...any) {
	if len(args) > 0 {
		_mock.Called(ctx, msg, args)
	} else {
		_mock.Called(ctx, msg)
	}

	return
}

// MockLogger_ErrorContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ErrorContext'
type MockLogger_ErrorContext_Call struct {
	*mock.Call
}

// ErrorContext is a helper method to define mock.On call
//   - ctx context.Context
//   - msg string
//   - args ...any
func (_e *MockLogger_Expecter) ErrorContext(ctx interface{}, msg interface{}, args ...interface{}) *MockLogger_ErrorContext_Call {
	return &MockLogger_ErrorContext_Call{Call: _e.mock.On("ErrorContext",
		append([]interface{}{ctx, msg}, args...)...)}
}

func (_c *MockLogger_ErrorContext_Call) Run(run func(ctx context.Context, msg string, args ...any)) *MockLogger_ErrorContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []any
		var variadicArgs []any
		if len(args) > 2 {
			variadicArgs = args[2].([]any)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockLogger_ErrorContext_Call) Return() *MockLogger_ErrorContext_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockLogger_ErrorContext_Call) RunAndReturn(run func(ctx context.Context, msg string, args ...any)) *MockLogger_ErrorContext_Call {
	_c.Run(run)
	return _c
}

// InfoContext provides a mock function for the type MockLogger
func (_mock *MockLogger) InfoContext(ctx context.Context, msg string, args ...any) {
	if len(args) > 0 {
		_mock.Called(ctx, msg, args)
	} else {
		_mock.Called(ctx, msg)
	}

	return
}

// MockLogger_InfoContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InfoContext'
type MockLogger_InfoContext_Call struct {
	*mock.Call
}

// InfoContext is a helper method to define mock.On call
//   - ctx context.Context
//   - msg string
//   - args ...any
func (_e *MockLogger_Expecter) InfoContext(ctx interface{}, msg interface{}, args ...interface{}) *MockLogger_InfoContext_Call {
	return &MockLogger_InfoContext_Call{Call: _e.mock.On("InfoContext",
		append([]interface{}{ctx, msg}, args...)...)}
}

func (_c *MockLogger_InfoContext_Call) Run(run func(ctx context.Context, msg string, args ...any)) *MockLogger_InfoContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []any
		var variadicArgs []any
		if len(args) > 2 {
			variadicArgs = args[2].([]any)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockLogger_InfoContext_Call) Return() *MockLogger_InfoContext_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockLogger_InfoContext_Call) RunAndReturn(run func(ctx context.Context, msg string, args ...any)) *MockLogger_InfoContext_Call {
	_c.Run(run)
	return _c
}

// Log provides a mock function for the type MockLogger
func (_mock *MockLogger) Log(ctx context.Context, level logs.Level, msg string, args ...any) {
	if len(args) > 0 {
		_mock.Called(ctx, level, msg, args)
	} else {
		_mock.Called(ctx, level, msg)
	}

	return
}

// MockLogger_Log_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Log'
type MockLogger_Log_Call struct {
	*mock.Call
}

// Log is a helper method to define mock.On call
//   - ctx context.Context
//   - level logger.Level
//   - msg string
//   - args ...any
func (_e *MockLogger_Expecter) Log(ctx interface{}, level interface{}, msg interface{}, args ...interface{}) *MockLogger_Log_Call {
	return &MockLogger_Log_Call{Call: _e.mock.On("Log",
		append([]interface{}{ctx, level, msg}, args...)...)}
}

func (_c *MockLogger_Log_Call) Run(run func(ctx context.Context, level logs.Level, msg string, args ...any)) *MockLogger_Log_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 logs.Level
		if args[1] != nil {
			arg1 = args[1].(logs.Level)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 []any
		var variadicArgs []any
		if len(args) > 3 {
			variadicArgs = args[3].([]any)
		}
		arg3 = variadicArgs
		run(
			arg0,
			arg1,
			arg2,
			arg3...,
		)
	})
	return _c
}

func (_c *MockLogger_Log_Call) Return() *MockLogger_Log_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockLogger_Log_Call) RunAndReturn(run func(ctx context.Context, level logs.Level, msg string, args ...any)) *MockLogger_Log_Call {
	_c.Run(run)
	return _c
}

// WarnContext provides a mock function for the type MockLogger
func (_mock *MockLogger) WarnContext(ctx context.Context, msg string, args ...any) {
	if len(args) > 0 {
		_mock.Called(ctx, msg, args)
	} else {
		_mock.Called(ctx, msg)
	}

	return
}

// MockLogger_WarnContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WarnContext'
type MockLogger_WarnContext_Call struct {
	*mock.Call
}

// WarnContext is a helper method to define mock.On call
//   - ctx context.Context
//   - msg string
//   - args ...any
func (_e *MockLogger_Expecter) WarnContext(ctx interface{}, msg interface{}, args ...interface{}) *MockLogger_WarnContext_Call {
	return &MockLogger_WarnContext_Call{Call: _e.mock.On("WarnContext",
		append([]interface{}{ctx, msg}, args...)...)}
}

func (_c *MockLogger_WarnContext_Call) Run(run func(ctx context.Context, msg string, args ...any)) *MockLogger_WarnContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []any
		var variadicArgs []any
		if len(args) > 2 {
			variadicArgs = args[2].([]any)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockLogger_WarnContext_Call) Return() *MockLogger_WarnContext_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockLogger_WarnContext_Call) RunAndReturn(run func(ctx context.Context, msg string, args ...any)) *MockLogger_WarnContext_Call {
	_c.Run(run)
	return _c
}

// With provides a mock function for the type MockLogger
func (_mock *MockLogger) With(args ...any) logs.Logger {
	var tmpRet mock.Arguments
	if len(args) > 0 {
		tmpRet = _mock.Called(args)
	} else {
		tmpRet = _mock.Called()
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for With")
	}

	var r0 logs.Logger
	if returnFunc, ok := ret.Get(0).(func(...any) logs.Logger); ok {
		r0 = returnFunc(args...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(logs.Logger)
		}
	}
	return r0
}

// MockLogger_With_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'With'
type MockLogger_With_Call struct {
	*mock.Call
}

// With is a helper method to define mock.On call
//   - args ...any
func (_e *MockLogger_Expecter) With(args ...interface{}) *MockLogger_With_Call {
	return &MockLogger_With_Call{Call: _e.mock.On("With",
		append([]interface{}{}, args...)...)}
}

func (_c *MockLogger_With_Call) Run(run func(args ...any)) *MockLogger_With_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []any
		var variadicArgs []any
		if len(args) > 0 {
			variadicArgs = args[0].([]any)
		}
		arg0 = variadicArgs
		run(
			arg0...,
		)
	})
	return _c
}

func (_c *MockLogger_With_Call) Return(logger1 logs.Logger) *MockLogger_With_Call {
	_c.Call.Return(logger1)
	return _c
}

func (_c *MockLogger_With_Call) RunAndReturn(run func(args ...any) logs.Logger) *MockLogger_With_Call {
	_c.Call.Return(run)
	return _c
}
