// Package dtos provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package dtos

import (
	"encoding/json"
	"fmt"
	"time"

	"github.com/OJOMB/fightpicker/pkg/id"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes = "BearerAuth.Scopes"
)

// Defines values for FighterResponseGender.
const (
	FighterResponseGenderFemale FighterResponseGender = "female"
	FighterResponseGenderMale   FighterResponseGender = "male"
	FighterResponseGenderOther  FighterResponseGender = "other"
)

// Defines values for UserCreateReqGender.
const (
	UserCreateReqGenderFemale UserCreateReqGender = "female"
	UserCreateReqGenderMale   UserCreateReqGender = "male"
	UserCreateReqGenderOther  UserCreateReqGender = "other"
)

// Defines values for UserResponseGender.
const (
	UserResponseGenderFemale UserResponseGender = "female"
	UserResponseGenderMale   UserResponseGender = "male"
	UserResponseGenderOther  UserResponseGender = "other"
)

// Defines values for UserUpdateReqGender.
const (
	UserUpdateReqGenderFemale UserUpdateReqGender = "female"
	UserUpdateReqGenderMale   UserUpdateReqGender = "male"
	UserUpdateReqGenderOther  UserUpdateReqGender = "other"
)

// AuthResponse defines model for AuthResponse.
type AuthResponse struct {
	AccessToken string `json:"access_token"`
}

// ErrorEnvelope Standard API error wrapper
type ErrorEnvelope struct {
	// Error Machine-readable error structure
	Error ErrorObject `json:"error"`
}

// ErrorObject Machine-readable error structure
type ErrorObject struct {
	// Code Application-level error code (NOT HTTP status)
	Code string `json:"code"`

	// Message Human-readable explanation of the error
	Message string `json:"message"`

	// RequestId Correlation ID for tracing the request
	RequestId string `json:"request_id"`
}

// FighterResponse defines model for FighterResponse.
type FighterResponse struct {
	Bio               string                `json:"bio"`
	Country           string                `json:"country"`
	CreatedAt         time.Time             `json:"created_at"`
	CreatedBy         id.UUID7              `json:"created_by"`
	Disqualifications int                   `json:"disqualifications"`
	Dob               SimpleDate            `json:"dob"`
	Draws             int                   `json:"draws"`
	FightingOutOf     string                `json:"fighting_out_of"`
	FirstName         string                `json:"first_name"`
	Gender            FighterResponseGender `json:"gender"`
	Height            float64               `json:"height"`
	Id                id.UUID7              `json:"id"`
	LastName          string                `json:"last_name"`
	Losses            int                   `json:"losses"`
	Nickname          string                `json:"nickname"`
	NoContests        int                   `json:"no_contests"`
	ProfilePicture    string                `json:"profile_picture"`
	Reach             float64               `json:"reach"`
	Stance            string                `json:"stance"`
	UpdatedAt         time.Time             `json:"updated_at"`
	UpdatedBy         id.UUID7              `json:"updated_by"`
	Weight            float64               `json:"weight"`
	Wins              int                   `json:"wins"`
}

// FighterResponseGender defines model for FighterResponse.Gender.
type FighterResponseGender string

// ListUsersResponse Paginated list of users.
// presigned profile picture URLs are ommitted in this response for performance reasons.
type ListUsersResponse struct {
	LastSeenId *id.UUID7 `json:"last_seen_id"`
	PageSize   int       `json:"page_size"`

	// TotalCount Total number of users available (ignoring pagination). Useful for clients to understand the size of the dataset.
	// if filtering by email or username is used, this will be either 0 or 1.
	TotalCount int            `json:"total_count"`
	Users      []UserResponse `json:"users"`
}

// LoginRequest User login request body
type LoginRequest struct {
	Email    openapi_types.Email `json:"email"`
	Password string              `json:"password"`
}

// SimpleDate defines model for SimpleDate.
type SimpleDate = openapi_types.Date

// UserCreateReq defines model for UserCreateReq.
type UserCreateReq struct {
	Bio       *string             `json:"bio,omitempty"`
	Dob       SimpleDate          `json:"dob"`
	Email     openapi_types.Email `json:"email"`
	FirstName string              `json:"first_name"`
	Gender    UserCreateReqGender `json:"gender"`
	LastName  string              `json:"last_name"`
	Location  *string             `json:"location,omitempty"`
	Password  string              `json:"password"`
	Username  string              `json:"username"`
}

// UserCreateReqGender defines model for UserCreateReq.Gender.
type UserCreateReqGender string

// UserProfilePictureUploadURLRequest defines model for UserProfilePictureUploadURLRequest.
type UserProfilePictureUploadURLRequest struct {
	// ContentType MIME type of the profile picture (e.g., image/jpeg, image/png)
	ContentType string `json:"content_type"`
}

// UserProfilePictureUploadURLResponse defines model for UserProfilePictureUploadURLResponse.
type UserProfilePictureUploadURLResponse struct {
	SignedHeader map[string]string `json:"signed_header"`
	UploadUrl    string            `json:"upload_url"`
}

// UserResponse defines model for UserResponse.
type UserResponse struct {
	Bio           string               `json:"bio"`
	CreatedAt     time.Time            `json:"created_at"`
	Dob           *SimpleDate          `json:"dob,omitempty"`
	Email         *openapi_types.Email `json:"email,omitempty"`
	EmailVerified *bool                `json:"email_verified,omitempty"`
	FirstName     *string              `json:"first_name,omitempty"`
	Gender        UserResponseGender   `json:"gender"`
	Id            id.UUID7             `json:"id"`
	LastLogin     *time.Time           `json:"last_login"`
	LastName      *string              `json:"last_name,omitempty"`
	Location      *string              `json:"location,omitempty"`

	// ProfilePicture Presigned URL to access the user's profile picture - may be null if a profile picture has not been set
	ProfilePicture *string   `json:"profile_picture,omitempty"`
	UpdatedAt      time.Time `json:"updated_at"`
	Username       string    `json:"username"`
}

// UserResponseGender defines model for UserResponse.Gender.
type UserResponseGender string

// UserUpdateReq defines model for UserUpdateReq.
type UserUpdateReq struct {
	Bio       *string              `json:"bio,omitempty"`
	Dob       *SimpleDate          `json:"dob,omitempty"`
	Email     *openapi_types.Email `json:"email,omitempty"`
	FirstName *string              `json:"first_name,omitempty"`
	Gender    *UserUpdateReqGender `json:"gender,omitempty"`
	LastName  *string              `json:"last_name,omitempty"`
	Location  *string              `json:"location,omitempty"`
	Password  *string              `json:"password,omitempty"`
	Username  *string              `json:"username,omitempty"`
	union     json.RawMessage
}

// UserUpdateReqGender defines model for UserUpdateReq.Gender.
type UserUpdateReqGender string

// UserUpdateReq0 defines model for .
type UserUpdateReq0 = interface{}

// UserUpdateReq1 defines model for .
type UserUpdateReq1 = interface{}

// UserUpdateReq2 defines model for .
type UserUpdateReq2 = interface{}

// UserUpdateReq3 defines model for .
type UserUpdateReq3 = interface{}

// UserUpdateReq4 defines model for .
type UserUpdateReq4 = interface{}

// UserUpdateReq5 defines model for .
type UserUpdateReq5 = interface{}

// UserUpdateReq6 defines model for .
type UserUpdateReq6 = interface{}

// UserUpdateReq7 defines model for .
type UserUpdateReq7 = interface{}

// V1UsersGetListParams defines parameters for V1UsersGetList.
type V1UsersGetListParams struct {
	LastSeenId *id.UUID7 `form:"last_seen_id,omitempty" json:"last_seen_id,omitempty"`
	PageSize   *int      `form:"page_size,omitempty" json:"page_size,omitempty"`

	// Email will return a user matching the email exactly or empty array if none found (admin only)
	// cannot be used in combination with the pagination parameters (last_seen_id, page_size)
	Email *string `form:"email,omitempty" json:"email,omitempty"`

	// Username will return a user matching the username exactly or empty array if none found
	// cannot be used in combination with the pagination parameters (last_seen_id, page_size)
	Username *string `form:"username,omitempty" json:"username,omitempty"`
}

// V1UsersGetVerifyEmailParams defines parameters for V1UsersGetVerifyEmail.
type V1UsersGetVerifyEmailParams struct {
	Token string `form:"token" json:"token"`
}

// V1UsersGetFollowingParams defines parameters for V1UsersGetFollowing.
type V1UsersGetFollowingParams struct {
	LastSeenId *id.UUID7 `form:"last_seen_id,omitempty" json:"last_seen_id,omitempty"`
	PageSize   *int      `form:"page_size,omitempty" json:"page_size,omitempty"`
}

// V1UsersGetFollowersParams defines parameters for V1UsersGetFollowers.
type V1UsersGetFollowersParams struct {
	LastSeenId *id.UUID7 `form:"last_seen_id,omitempty" json:"last_seen_id,omitempty"`
	PageSize   *int      `form:"page_size,omitempty" json:"page_size,omitempty"`
}

// V1AuthPostLoginJSONRequestBody defines body for V1AuthPostLogin for application/json ContentType.
type V1AuthPostLoginJSONRequestBody = LoginRequest

// V1UsersPostCreateJSONRequestBody defines body for V1UsersPostCreate for application/json ContentType.
type V1UsersPostCreateJSONRequestBody = UserCreateReq

// UpdateUserByIDV1JSONRequestBody defines body for UpdateUserByIDV1 for application/json ContentType.
type UpdateUserByIDV1JSONRequestBody = UserUpdateReq

// V1UsersPostGeneratePresignedUrlJSONRequestBody defines body for V1UsersPostGeneratePresignedUrl for application/json ContentType.
type V1UsersPostGeneratePresignedUrlJSONRequestBody = UserProfilePictureUploadURLRequest

// AsUserUpdateReq0 returns the union data inside the UserUpdateReq as a UserUpdateReq0
func (t UserUpdateReq) AsUserUpdateReq0() (UserUpdateReq0, error) {
	var body UserUpdateReq0
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromUserUpdateReq0 overwrites any union data inside the UserUpdateReq as the provided UserUpdateReq0
func (t *UserUpdateReq) FromUserUpdateReq0(v UserUpdateReq0) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeUserUpdateReq0 performs a merge with any union data inside the UserUpdateReq, using the provided UserUpdateReq0
func (t *UserUpdateReq) MergeUserUpdateReq0(v UserUpdateReq0) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsUserUpdateReq1 returns the union data inside the UserUpdateReq as a UserUpdateReq1
func (t UserUpdateReq) AsUserUpdateReq1() (UserUpdateReq1, error) {
	var body UserUpdateReq1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromUserUpdateReq1 overwrites any union data inside the UserUpdateReq as the provided UserUpdateReq1
func (t *UserUpdateReq) FromUserUpdateReq1(v UserUpdateReq1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeUserUpdateReq1 performs a merge with any union data inside the UserUpdateReq, using the provided UserUpdateReq1
func (t *UserUpdateReq) MergeUserUpdateReq1(v UserUpdateReq1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsUserUpdateReq2 returns the union data inside the UserUpdateReq as a UserUpdateReq2
func (t UserUpdateReq) AsUserUpdateReq2() (UserUpdateReq2, error) {
	var body UserUpdateReq2
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromUserUpdateReq2 overwrites any union data inside the UserUpdateReq as the provided UserUpdateReq2
func (t *UserUpdateReq) FromUserUpdateReq2(v UserUpdateReq2) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeUserUpdateReq2 performs a merge with any union data inside the UserUpdateReq, using the provided UserUpdateReq2
func (t *UserUpdateReq) MergeUserUpdateReq2(v UserUpdateReq2) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsUserUpdateReq3 returns the union data inside the UserUpdateReq as a UserUpdateReq3
func (t UserUpdateReq) AsUserUpdateReq3() (UserUpdateReq3, error) {
	var body UserUpdateReq3
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromUserUpdateReq3 overwrites any union data inside the UserUpdateReq as the provided UserUpdateReq3
func (t *UserUpdateReq) FromUserUpdateReq3(v UserUpdateReq3) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeUserUpdateReq3 performs a merge with any union data inside the UserUpdateReq, using the provided UserUpdateReq3
func (t *UserUpdateReq) MergeUserUpdateReq3(v UserUpdateReq3) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsUserUpdateReq4 returns the union data inside the UserUpdateReq as a UserUpdateReq4
func (t UserUpdateReq) AsUserUpdateReq4() (UserUpdateReq4, error) {
	var body UserUpdateReq4
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromUserUpdateReq4 overwrites any union data inside the UserUpdateReq as the provided UserUpdateReq4
func (t *UserUpdateReq) FromUserUpdateReq4(v UserUpdateReq4) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeUserUpdateReq4 performs a merge with any union data inside the UserUpdateReq, using the provided UserUpdateReq4
func (t *UserUpdateReq) MergeUserUpdateReq4(v UserUpdateReq4) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsUserUpdateReq5 returns the union data inside the UserUpdateReq as a UserUpdateReq5
func (t UserUpdateReq) AsUserUpdateReq5() (UserUpdateReq5, error) {
	var body UserUpdateReq5
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromUserUpdateReq5 overwrites any union data inside the UserUpdateReq as the provided UserUpdateReq5
func (t *UserUpdateReq) FromUserUpdateReq5(v UserUpdateReq5) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeUserUpdateReq5 performs a merge with any union data inside the UserUpdateReq, using the provided UserUpdateReq5
func (t *UserUpdateReq) MergeUserUpdateReq5(v UserUpdateReq5) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsUserUpdateReq6 returns the union data inside the UserUpdateReq as a UserUpdateReq6
func (t UserUpdateReq) AsUserUpdateReq6() (UserUpdateReq6, error) {
	var body UserUpdateReq6
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromUserUpdateReq6 overwrites any union data inside the UserUpdateReq as the provided UserUpdateReq6
func (t *UserUpdateReq) FromUserUpdateReq6(v UserUpdateReq6) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeUserUpdateReq6 performs a merge with any union data inside the UserUpdateReq, using the provided UserUpdateReq6
func (t *UserUpdateReq) MergeUserUpdateReq6(v UserUpdateReq6) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsUserUpdateReq7 returns the union data inside the UserUpdateReq as a UserUpdateReq7
func (t UserUpdateReq) AsUserUpdateReq7() (UserUpdateReq7, error) {
	var body UserUpdateReq7
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromUserUpdateReq7 overwrites any union data inside the UserUpdateReq as the provided UserUpdateReq7
func (t *UserUpdateReq) FromUserUpdateReq7(v UserUpdateReq7) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeUserUpdateReq7 performs a merge with any union data inside the UserUpdateReq, using the provided UserUpdateReq7
func (t *UserUpdateReq) MergeUserUpdateReq7(v UserUpdateReq7) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t UserUpdateReq) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	if err != nil {
		return nil, err
	}
	object := make(map[string]json.RawMessage)
	if t.union != nil {
		err = json.Unmarshal(b, &object)
		if err != nil {
			return nil, err
		}
	}

	if t.Bio != nil {
		object["bio"], err = json.Marshal(t.Bio)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'bio': %w", err)
		}
	}

	if t.Dob != nil {
		object["dob"], err = json.Marshal(t.Dob)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'dob': %w", err)
		}
	}

	if t.Email != nil {
		object["email"], err = json.Marshal(t.Email)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'email': %w", err)
		}
	}

	if t.FirstName != nil {
		object["first_name"], err = json.Marshal(t.FirstName)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'first_name': %w", err)
		}
	}

	if t.Gender != nil {
		object["gender"], err = json.Marshal(t.Gender)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'gender': %w", err)
		}
	}

	if t.LastName != nil {
		object["last_name"], err = json.Marshal(t.LastName)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'last_name': %w", err)
		}
	}

	if t.Location != nil {
		object["location"], err = json.Marshal(t.Location)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'location': %w", err)
		}
	}

	if t.Password != nil {
		object["password"], err = json.Marshal(t.Password)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'password': %w", err)
		}
	}

	if t.Username != nil {
		object["username"], err = json.Marshal(t.Username)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'username': %w", err)
		}
	}
	b, err = json.Marshal(object)
	return b, err
}

func (t *UserUpdateReq) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	if err != nil {
		return err
	}
	object := make(map[string]json.RawMessage)
	err = json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["bio"]; found {
		err = json.Unmarshal(raw, &t.Bio)
		if err != nil {
			return fmt.Errorf("error reading 'bio': %w", err)
		}
	}

	if raw, found := object["dob"]; found {
		err = json.Unmarshal(raw, &t.Dob)
		if err != nil {
			return fmt.Errorf("error reading 'dob': %w", err)
		}
	}

	if raw, found := object["email"]; found {
		err = json.Unmarshal(raw, &t.Email)
		if err != nil {
			return fmt.Errorf("error reading 'email': %w", err)
		}
	}

	if raw, found := object["first_name"]; found {
		err = json.Unmarshal(raw, &t.FirstName)
		if err != nil {
			return fmt.Errorf("error reading 'first_name': %w", err)
		}
	}

	if raw, found := object["gender"]; found {
		err = json.Unmarshal(raw, &t.Gender)
		if err != nil {
			return fmt.Errorf("error reading 'gender': %w", err)
		}
	}

	if raw, found := object["last_name"]; found {
		err = json.Unmarshal(raw, &t.LastName)
		if err != nil {
			return fmt.Errorf("error reading 'last_name': %w", err)
		}
	}

	if raw, found := object["location"]; found {
		err = json.Unmarshal(raw, &t.Location)
		if err != nil {
			return fmt.Errorf("error reading 'location': %w", err)
		}
	}

	if raw, found := object["password"]; found {
		err = json.Unmarshal(raw, &t.Password)
		if err != nil {
			return fmt.Errorf("error reading 'password': %w", err)
		}
	}

	if raw, found := object["username"]; found {
		err = json.Unmarshal(raw, &t.Username)
		if err != nil {
			return fmt.Errorf("error reading 'username': %w", err)
		}
	}

	return err
}
