// Package dtos provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package dtos

import (
	"encoding/json"
	"fmt"
	"time"

	"github.com/OJOMB/fightpicker/pkg/id"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes = "BearerAuth.Scopes"
)

// Defines values for FighterCreateReqGender.
const (
	FighterCreateReqGenderFemale FighterCreateReqGender = "female"
	FighterCreateReqGenderMale   FighterCreateReqGender = "male"
	FighterCreateReqGenderOther  FighterCreateReqGender = "other"
)

// Defines values for FighterIngestionResultStatus.
const (
	Created FighterIngestionResultStatus = "created"
	Failed  FighterIngestionResultStatus = "failed"
	Skipped FighterIngestionResultStatus = "skipped"
	Updated FighterIngestionResultStatus = "updated"
)

// Defines values for FighterResponseGender.
const (
	FighterResponseGenderFemale FighterResponseGender = "female"
	FighterResponseGenderMale   FighterResponseGender = "male"
	FighterResponseGenderOther  FighterResponseGender = "other"
)

// Defines values for FighterUpdateReqGender.
const (
	FighterUpdateReqGenderFemale FighterUpdateReqGender = "female"
	FighterUpdateReqGenderMale   FighterUpdateReqGender = "male"
	FighterUpdateReqGenderOther  FighterUpdateReqGender = "other"
)

// Defines values for UserCreateReqGender.
const (
	UserCreateReqGenderFemale UserCreateReqGender = "female"
	UserCreateReqGenderMale   UserCreateReqGender = "male"
	UserCreateReqGenderOther  UserCreateReqGender = "other"
)

// Defines values for UserResponseGender.
const (
	UserResponseGenderFemale UserResponseGender = "female"
	UserResponseGenderMale   UserResponseGender = "male"
	UserResponseGenderOther  UserResponseGender = "other"
)

// Defines values for UserUpdateReqGender.
const (
	UserUpdateReqGenderFemale UserUpdateReqGender = "female"
	UserUpdateReqGenderMale   UserUpdateReqGender = "male"
	UserUpdateReqGenderOther  UserUpdateReqGender = "other"
)

// AuthResponse Authentication response.
// The refresh token is issued via an HttpOnly cookie and is not included in the response body.
type AuthResponse struct {
	AccessToken string `json:"access_token"`
}

// ErrorEnvelope Standard API error wrapper
type ErrorEnvelope struct {
	// Error Machine-readable error structure
	Error ErrorObject `json:"error"`
}

// ErrorObject Machine-readable error structure
type ErrorObject struct {
	// Code Application-level error code (NOT HTTP status)
	Code string `json:"code"`

	// Message Human-readable explanation of the error
	Message string `json:"message"`

	// RequestId Correlation ID for tracing the request
	RequestId string `json:"request_id"`
}

// FighterCreateReq defines model for FighterCreateReq.
type FighterCreateReq struct {
	Bio               string                 `json:"bio"`
	Country           string                 `json:"country"`
	Disqualifications int                    `json:"disqualifications"`
	Dob               SimpleDate             `json:"dob"`
	Draws             int                    `json:"draws"`
	FightingOutOf     string                 `json:"fighting_out_of"`
	FirstName         string                 `json:"first_name"`
	Gender            FighterCreateReqGender `json:"gender"`
	Height            float64                `json:"height"`
	LastName          string                 `json:"last_name"`
	Losses            int                    `json:"losses"`
	Nickname          *string                `json:"nickname,omitempty"`
	NoContests        int                    `json:"no_contests"`
	Reach             float64                `json:"reach"`
	Stance            string                 `json:"stance"`
	Weight            float64                `json:"weight"`
	Wins              int                    `json:"wins"`
}

// FighterCreateReqGender defines model for FighterCreateReq.Gender.
type FighterCreateReqGender string

// FighterIngestionResult defines model for FighterIngestionResult.
type FighterIngestionResult struct {
	// Error Machine-readable error structure
	Error *ErrorObject `json:"error,omitempty"`

	// FighterId Present when status is created or updated
	FighterId *id.UUID7 `json:"fighter_id,omitempty"`

	// Index Index of the item in the request array
	Index  int                          `json:"index"`
	Status FighterIngestionResultStatus `json:"status"`
}

// FighterIngestionResultStatus defines model for FighterIngestionResult.Status.
type FighterIngestionResultStatus string

// FighterResponse defines model for FighterResponse.
type FighterResponse struct {
	Bio               string                `json:"bio"`
	Country           string                `json:"country"`
	CreatedAt         time.Time             `json:"created_at"`
	CreatedBy         id.UUID7              `json:"created_by"`
	Disqualifications int                   `json:"disqualifications"`
	Dob               SimpleDate            `json:"dob"`
	Draws             int                   `json:"draws"`
	FightingOutOf     string                `json:"fighting_out_of"`
	FirstName         string                `json:"first_name"`
	Gender            FighterResponseGender `json:"gender"`
	Height            float64               `json:"height"`
	Id                id.UUID7              `json:"id"`
	LastName          string                `json:"last_name"`
	Losses            int                   `json:"losses"`
	Nickname          string                `json:"nickname"`
	NoContests        int                   `json:"no_contests"`
	ProfilePicture    string                `json:"profile_picture"`
	Reach             float64               `json:"reach"`
	Stance            string                `json:"stance"`
	UpdatedAt         time.Time             `json:"updated_at"`
	UpdatedBy         id.UUID7              `json:"updated_by"`
	Weight            float64               `json:"weight"`
	Wins              int                   `json:"wins"`
}

// FighterResponseGender defines model for FighterResponse.Gender.
type FighterResponseGender string

// FighterUpdateReq defines model for FighterUpdateReq.
type FighterUpdateReq struct {
	Bio               *string                 `json:"bio,omitempty"`
	Country           *string                 `json:"country,omitempty"`
	Disqualifications *int                    `json:"disqualifications,omitempty"`
	Dob               *SimpleDate             `json:"dob,omitempty"`
	Draws             *int                    `json:"draws,omitempty"`
	FightingOutOf     *string                 `json:"fighting_out_of,omitempty"`
	FirstName         *string                 `json:"first_name,omitempty"`
	Gender            *FighterUpdateReqGender `json:"gender,omitempty"`
	Height            *float64                `json:"height,omitempty"`
	LastName          *string                 `json:"last_name,omitempty"`
	Losses            *int                    `json:"losses,omitempty"`
	Nickname          *string                 `json:"nickname,omitempty"`
	NoContests        *int                    `json:"no_contests,omitempty"`
	Reach             *float64                `json:"reach,omitempty"`
	Stance            *string                 `json:"stance,omitempty"`
	Weight            *float64                `json:"weight,omitempty"`
	Wins              *int                    `json:"wins,omitempty"`
	union             json.RawMessage
}

// FighterUpdateReqGender defines model for FighterUpdateReq.Gender.
type FighterUpdateReqGender string

// FighterUpdateReq0 defines model for .
type FighterUpdateReq0 = interface{}

// FighterUpdateReq1 defines model for .
type FighterUpdateReq1 = interface{}

// FighterUpdateReq2 defines model for .
type FighterUpdateReq2 = interface{}

// FighterUpdateReq3 defines model for .
type FighterUpdateReq3 = interface{}

// FighterUpdateReq4 defines model for .
type FighterUpdateReq4 = interface{}

// FighterUpdateReq5 defines model for .
type FighterUpdateReq5 = interface{}

// FighterUpdateReq6 defines model for .
type FighterUpdateReq6 = interface{}

// FighterUpdateReq7 defines model for .
type FighterUpdateReq7 = interface{}

// FighterUpdateReq8 defines model for .
type FighterUpdateReq8 = interface{}

// FighterUpdateReq9 defines model for .
type FighterUpdateReq9 = interface{}

// FighterUpdateReq10 defines model for .
type FighterUpdateReq10 = interface{}

// FighterUpdateReq11 defines model for .
type FighterUpdateReq11 = interface{}

// FighterUpdateReq12 defines model for .
type FighterUpdateReq12 = interface{}

// FighterUpdateReq13 defines model for .
type FighterUpdateReq13 = interface{}

// FighterUpdateReq14 defines model for .
type FighterUpdateReq14 = interface{}

// FighterUpdateReq15 defines model for .
type FighterUpdateReq15 = interface{}

// FighterUpdateReq16 defines model for .
type FighterUpdateReq16 = interface{}

// FightersIngestionReq defines model for FightersIngestionReq.
type FightersIngestionReq = []FighterCreateReq

// FightersIngestionResp defines model for FightersIngestionResp.
type FightersIngestionResp struct {
	Results []FighterIngestionResult `json:"results"`
	Summary FightersIngestionSummary `json:"summary"`
}

// FightersIngestionSummary defines model for FightersIngestionSummary.
type FightersIngestionSummary struct {
	Created int `json:"created"`
	Failed  int `json:"failed"`
	Skipped int `json:"skipped"`
	Total   int `json:"total"`
	Updated int `json:"updated"`
}

// ListFightersResponse Paginated list of fighters.
type ListFightersResponse struct {
	Fighters   []FighterResponse `json:"fighters"`
	LastSeenId *id.UUID7         `json:"last_seen_id"`
	PageSize   int               `json:"page_size"`

	// TotalCount Total number of fighters available (ignoring pagination). Useful for clients to understand the size of the dataset.
	// if filtering by email or username is used, this will be either 0 or 1.
	TotalCount int `json:"total_count"`
}

// ListUsersResponse Paginated list of users.
// presigned profile picture URLs are ommitted in this response for performance reasons.
type ListUsersResponse struct {
	LastSeenId *id.UUID7 `json:"last_seen_id"`
	PageSize   int       `json:"page_size"`

	// TotalCount Total number of users available (ignoring pagination). Useful for clients to understand the size of the dataset.
	// if filtering by email or username is used, this will be either 0 or 1.
	TotalCount int            `json:"total_count"`
	Users      []UserResponse `json:"users"`
}

// LoginRequest User login request body
type LoginRequest struct {
	Email    openapi_types.Email `json:"email"`
	Password string              `json:"password"`
}

// SimpleDate defines model for SimpleDate.
type SimpleDate = openapi_types.Date

// UserCreateReq defines model for UserCreateReq.
type UserCreateReq struct {
	Bio       *string             `json:"bio,omitempty"`
	Dob       SimpleDate          `json:"dob"`
	Email     openapi_types.Email `json:"email"`
	FirstName string              `json:"first_name"`
	Gender    UserCreateReqGender `json:"gender"`
	LastName  string              `json:"last_name"`
	Location  *string             `json:"location,omitempty"`
	Password  string              `json:"password"`
	Username  string              `json:"username"`
}

// UserCreateReqGender defines model for UserCreateReq.Gender.
type UserCreateReqGender string

// UserProfilePictureUploadURLRequest defines model for UserProfilePictureUploadURLRequest.
type UserProfilePictureUploadURLRequest struct {
	// ContentType MIME type of the profile picture (e.g., image/jpeg, image/png)
	ContentType string `json:"content_type"`
}

// UserProfilePictureUploadURLResponse defines model for UserProfilePictureUploadURLResponse.
type UserProfilePictureUploadURLResponse struct {
	SignedHeader map[string]string `json:"signed_header"`
	UploadUrl    string            `json:"upload_url"`
}

// UserResponse defines model for UserResponse.
type UserResponse struct {
	Bio           string               `json:"bio"`
	CreatedAt     time.Time            `json:"created_at"`
	Dob           *SimpleDate          `json:"dob,omitempty"`
	Email         *openapi_types.Email `json:"email,omitempty"`
	EmailVerified *bool                `json:"email_verified,omitempty"`
	FirstName     *string              `json:"first_name,omitempty"`
	Gender        UserResponseGender   `json:"gender"`
	Id            id.UUID7             `json:"id"`
	LastLogin     *time.Time           `json:"last_login"`
	LastName      *string              `json:"last_name,omitempty"`
	Location      *string              `json:"location,omitempty"`

	// ProfilePicture Presigned URL to access the user's profile picture - may be null if a profile picture has not been set
	ProfilePicture *string   `json:"profile_picture,omitempty"`
	UpdatedAt      time.Time `json:"updated_at"`
	Username       string    `json:"username"`
}

// UserResponseGender defines model for UserResponse.Gender.
type UserResponseGender string

// UserUpdateReq defines model for UserUpdateReq.
type UserUpdateReq struct {
	Bio       *string              `json:"bio,omitempty"`
	Dob       *SimpleDate          `json:"dob,omitempty"`
	Email     *openapi_types.Email `json:"email,omitempty"`
	FirstName *string              `json:"first_name,omitempty"`
	Gender    *UserUpdateReqGender `json:"gender,omitempty"`
	LastName  *string              `json:"last_name,omitempty"`
	Location  *string              `json:"location,omitempty"`
	Password  *string              `json:"password,omitempty"`
	Username  *string              `json:"username,omitempty"`
	union     json.RawMessage
}

// UserUpdateReqGender defines model for UserUpdateReq.Gender.
type UserUpdateReqGender string

// UserUpdateReq0 defines model for .
type UserUpdateReq0 = interface{}

// UserUpdateReq1 defines model for .
type UserUpdateReq1 = interface{}

// UserUpdateReq2 defines model for .
type UserUpdateReq2 = interface{}

// UserUpdateReq3 defines model for .
type UserUpdateReq3 = interface{}

// UserUpdateReq4 defines model for .
type UserUpdateReq4 = interface{}

// UserUpdateReq5 defines model for .
type UserUpdateReq5 = interface{}

// UserUpdateReq6 defines model for .
type UserUpdateReq6 = interface{}

// UserUpdateReq7 defines model for .
type UserUpdateReq7 = interface{}

// V1FightersGetListParams defines parameters for V1FightersGetList.
type V1FightersGetListParams struct {
	LastSeenId *id.UUID7 `form:"last_seen_id,omitempty" json:"last_seen_id,omitempty"`
	PageSize   *int      `form:"page_size,omitempty" json:"page_size,omitempty"`
}

// V1FightersPostIngestParams defines parameters for V1FightersPostIngest.
type V1FightersPostIngestParams struct {
	// Upsert this is an admin-only operation
	// if true, existing fighters (matched by first_name, last_name, dob) will be updated with the new data provided
	// if false or omitted, an error will be returned if a fighter already exists with the same first_name, last_name and dob
	Upsert *bool `form:"upsert,omitempty" json:"upsert,omitempty"`
}

// V1UsersGetListParams defines parameters for V1UsersGetList.
type V1UsersGetListParams struct {
	LastSeenId *id.UUID7 `form:"last_seen_id,omitempty" json:"last_seen_id,omitempty"`
	PageSize   *int      `form:"page_size,omitempty" json:"page_size,omitempty"`

	// Email will return a user matching the email exactly or empty array if none found (admin only)
	// cannot be used in combination with the pagination parameters (last_seen_id, page_size)
	Email *string `form:"email,omitempty" json:"email,omitempty"`

	// Username will return a user matching the username exactly or empty array if none found
	// cannot be used in combination with the pagination parameters (last_seen_id, page_size)
	Username *string `form:"username,omitempty" json:"username,omitempty"`
}

// V1UsersGetVerifyEmailParams defines parameters for V1UsersGetVerifyEmail.
type V1UsersGetVerifyEmailParams struct {
	Token string `form:"token" json:"token"`
}

// V1UsersGetFollowingParams defines parameters for V1UsersGetFollowing.
type V1UsersGetFollowingParams struct {
	LastSeenId *id.UUID7 `form:"last_seen_id,omitempty" json:"last_seen_id,omitempty"`
	PageSize   *int      `form:"page_size,omitempty" json:"page_size,omitempty"`
}

// V1UsersGetFollowersParams defines parameters for V1UsersGetFollowers.
type V1UsersGetFollowersParams struct {
	LastSeenId *id.UUID7 `form:"last_seen_id,omitempty" json:"last_seen_id,omitempty"`
	PageSize   *int      `form:"page_size,omitempty" json:"page_size,omitempty"`
}

// V1AuthPostLoginJSONRequestBody defines body for V1AuthPostLogin for application/json ContentType.
type V1AuthPostLoginJSONRequestBody = LoginRequest

// V1FightersPatchUpdateJSONRequestBody defines body for V1FightersPatchUpdate for application/json ContentType.
type V1FightersPatchUpdateJSONRequestBody = FighterUpdateReq

// V1FightersPostIngestJSONRequestBody defines body for V1FightersPostIngest for application/json ContentType.
type V1FightersPostIngestJSONRequestBody = FightersIngestionReq

// V1UsersPostCreateJSONRequestBody defines body for V1UsersPostCreate for application/json ContentType.
type V1UsersPostCreateJSONRequestBody = UserCreateReq

// V1UsersPatchUpdateJSONRequestBody defines body for V1UsersPatchUpdate for application/json ContentType.
type V1UsersPatchUpdateJSONRequestBody = UserUpdateReq

// V1UsersPostGeneratePresignedUrlJSONRequestBody defines body for V1UsersPostGeneratePresignedUrl for application/json ContentType.
type V1UsersPostGeneratePresignedUrlJSONRequestBody = UserProfilePictureUploadURLRequest

// AsFighterUpdateReq0 returns the union data inside the FighterUpdateReq as a FighterUpdateReq0
func (t FighterUpdateReq) AsFighterUpdateReq0() (FighterUpdateReq0, error) {
	var body FighterUpdateReq0
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromFighterUpdateReq0 overwrites any union data inside the FighterUpdateReq as the provided FighterUpdateReq0
func (t *FighterUpdateReq) FromFighterUpdateReq0(v FighterUpdateReq0) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeFighterUpdateReq0 performs a merge with any union data inside the FighterUpdateReq, using the provided FighterUpdateReq0
func (t *FighterUpdateReq) MergeFighterUpdateReq0(v FighterUpdateReq0) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsFighterUpdateReq1 returns the union data inside the FighterUpdateReq as a FighterUpdateReq1
func (t FighterUpdateReq) AsFighterUpdateReq1() (FighterUpdateReq1, error) {
	var body FighterUpdateReq1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromFighterUpdateReq1 overwrites any union data inside the FighterUpdateReq as the provided FighterUpdateReq1
func (t *FighterUpdateReq) FromFighterUpdateReq1(v FighterUpdateReq1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeFighterUpdateReq1 performs a merge with any union data inside the FighterUpdateReq, using the provided FighterUpdateReq1
func (t *FighterUpdateReq) MergeFighterUpdateReq1(v FighterUpdateReq1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsFighterUpdateReq2 returns the union data inside the FighterUpdateReq as a FighterUpdateReq2
func (t FighterUpdateReq) AsFighterUpdateReq2() (FighterUpdateReq2, error) {
	var body FighterUpdateReq2
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromFighterUpdateReq2 overwrites any union data inside the FighterUpdateReq as the provided FighterUpdateReq2
func (t *FighterUpdateReq) FromFighterUpdateReq2(v FighterUpdateReq2) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeFighterUpdateReq2 performs a merge with any union data inside the FighterUpdateReq, using the provided FighterUpdateReq2
func (t *FighterUpdateReq) MergeFighterUpdateReq2(v FighterUpdateReq2) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsFighterUpdateReq3 returns the union data inside the FighterUpdateReq as a FighterUpdateReq3
func (t FighterUpdateReq) AsFighterUpdateReq3() (FighterUpdateReq3, error) {
	var body FighterUpdateReq3
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromFighterUpdateReq3 overwrites any union data inside the FighterUpdateReq as the provided FighterUpdateReq3
func (t *FighterUpdateReq) FromFighterUpdateReq3(v FighterUpdateReq3) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeFighterUpdateReq3 performs a merge with any union data inside the FighterUpdateReq, using the provided FighterUpdateReq3
func (t *FighterUpdateReq) MergeFighterUpdateReq3(v FighterUpdateReq3) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsFighterUpdateReq4 returns the union data inside the FighterUpdateReq as a FighterUpdateReq4
func (t FighterUpdateReq) AsFighterUpdateReq4() (FighterUpdateReq4, error) {
	var body FighterUpdateReq4
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromFighterUpdateReq4 overwrites any union data inside the FighterUpdateReq as the provided FighterUpdateReq4
func (t *FighterUpdateReq) FromFighterUpdateReq4(v FighterUpdateReq4) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeFighterUpdateReq4 performs a merge with any union data inside the FighterUpdateReq, using the provided FighterUpdateReq4
func (t *FighterUpdateReq) MergeFighterUpdateReq4(v FighterUpdateReq4) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsFighterUpdateReq5 returns the union data inside the FighterUpdateReq as a FighterUpdateReq5
func (t FighterUpdateReq) AsFighterUpdateReq5() (FighterUpdateReq5, error) {
	var body FighterUpdateReq5
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromFighterUpdateReq5 overwrites any union data inside the FighterUpdateReq as the provided FighterUpdateReq5
func (t *FighterUpdateReq) FromFighterUpdateReq5(v FighterUpdateReq5) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeFighterUpdateReq5 performs a merge with any union data inside the FighterUpdateReq, using the provided FighterUpdateReq5
func (t *FighterUpdateReq) MergeFighterUpdateReq5(v FighterUpdateReq5) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsFighterUpdateReq6 returns the union data inside the FighterUpdateReq as a FighterUpdateReq6
func (t FighterUpdateReq) AsFighterUpdateReq6() (FighterUpdateReq6, error) {
	var body FighterUpdateReq6
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromFighterUpdateReq6 overwrites any union data inside the FighterUpdateReq as the provided FighterUpdateReq6
func (t *FighterUpdateReq) FromFighterUpdateReq6(v FighterUpdateReq6) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeFighterUpdateReq6 performs a merge with any union data inside the FighterUpdateReq, using the provided FighterUpdateReq6
func (t *FighterUpdateReq) MergeFighterUpdateReq6(v FighterUpdateReq6) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsFighterUpdateReq7 returns the union data inside the FighterUpdateReq as a FighterUpdateReq7
func (t FighterUpdateReq) AsFighterUpdateReq7() (FighterUpdateReq7, error) {
	var body FighterUpdateReq7
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromFighterUpdateReq7 overwrites any union data inside the FighterUpdateReq as the provided FighterUpdateReq7
func (t *FighterUpdateReq) FromFighterUpdateReq7(v FighterUpdateReq7) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeFighterUpdateReq7 performs a merge with any union data inside the FighterUpdateReq, using the provided FighterUpdateReq7
func (t *FighterUpdateReq) MergeFighterUpdateReq7(v FighterUpdateReq7) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsFighterUpdateReq8 returns the union data inside the FighterUpdateReq as a FighterUpdateReq8
func (t FighterUpdateReq) AsFighterUpdateReq8() (FighterUpdateReq8, error) {
	var body FighterUpdateReq8
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromFighterUpdateReq8 overwrites any union data inside the FighterUpdateReq as the provided FighterUpdateReq8
func (t *FighterUpdateReq) FromFighterUpdateReq8(v FighterUpdateReq8) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeFighterUpdateReq8 performs a merge with any union data inside the FighterUpdateReq, using the provided FighterUpdateReq8
func (t *FighterUpdateReq) MergeFighterUpdateReq8(v FighterUpdateReq8) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsFighterUpdateReq9 returns the union data inside the FighterUpdateReq as a FighterUpdateReq9
func (t FighterUpdateReq) AsFighterUpdateReq9() (FighterUpdateReq9, error) {
	var body FighterUpdateReq9
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromFighterUpdateReq9 overwrites any union data inside the FighterUpdateReq as the provided FighterUpdateReq9
func (t *FighterUpdateReq) FromFighterUpdateReq9(v FighterUpdateReq9) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeFighterUpdateReq9 performs a merge with any union data inside the FighterUpdateReq, using the provided FighterUpdateReq9
func (t *FighterUpdateReq) MergeFighterUpdateReq9(v FighterUpdateReq9) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsFighterUpdateReq10 returns the union data inside the FighterUpdateReq as a FighterUpdateReq10
func (t FighterUpdateReq) AsFighterUpdateReq10() (FighterUpdateReq10, error) {
	var body FighterUpdateReq10
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromFighterUpdateReq10 overwrites any union data inside the FighterUpdateReq as the provided FighterUpdateReq10
func (t *FighterUpdateReq) FromFighterUpdateReq10(v FighterUpdateReq10) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeFighterUpdateReq10 performs a merge with any union data inside the FighterUpdateReq, using the provided FighterUpdateReq10
func (t *FighterUpdateReq) MergeFighterUpdateReq10(v FighterUpdateReq10) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsFighterUpdateReq11 returns the union data inside the FighterUpdateReq as a FighterUpdateReq11
func (t FighterUpdateReq) AsFighterUpdateReq11() (FighterUpdateReq11, error) {
	var body FighterUpdateReq11
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromFighterUpdateReq11 overwrites any union data inside the FighterUpdateReq as the provided FighterUpdateReq11
func (t *FighterUpdateReq) FromFighterUpdateReq11(v FighterUpdateReq11) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeFighterUpdateReq11 performs a merge with any union data inside the FighterUpdateReq, using the provided FighterUpdateReq11
func (t *FighterUpdateReq) MergeFighterUpdateReq11(v FighterUpdateReq11) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsFighterUpdateReq12 returns the union data inside the FighterUpdateReq as a FighterUpdateReq12
func (t FighterUpdateReq) AsFighterUpdateReq12() (FighterUpdateReq12, error) {
	var body FighterUpdateReq12
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromFighterUpdateReq12 overwrites any union data inside the FighterUpdateReq as the provided FighterUpdateReq12
func (t *FighterUpdateReq) FromFighterUpdateReq12(v FighterUpdateReq12) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeFighterUpdateReq12 performs a merge with any union data inside the FighterUpdateReq, using the provided FighterUpdateReq12
func (t *FighterUpdateReq) MergeFighterUpdateReq12(v FighterUpdateReq12) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsFighterUpdateReq13 returns the union data inside the FighterUpdateReq as a FighterUpdateReq13
func (t FighterUpdateReq) AsFighterUpdateReq13() (FighterUpdateReq13, error) {
	var body FighterUpdateReq13
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromFighterUpdateReq13 overwrites any union data inside the FighterUpdateReq as the provided FighterUpdateReq13
func (t *FighterUpdateReq) FromFighterUpdateReq13(v FighterUpdateReq13) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeFighterUpdateReq13 performs a merge with any union data inside the FighterUpdateReq, using the provided FighterUpdateReq13
func (t *FighterUpdateReq) MergeFighterUpdateReq13(v FighterUpdateReq13) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsFighterUpdateReq14 returns the union data inside the FighterUpdateReq as a FighterUpdateReq14
func (t FighterUpdateReq) AsFighterUpdateReq14() (FighterUpdateReq14, error) {
	var body FighterUpdateReq14
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromFighterUpdateReq14 overwrites any union data inside the FighterUpdateReq as the provided FighterUpdateReq14
func (t *FighterUpdateReq) FromFighterUpdateReq14(v FighterUpdateReq14) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeFighterUpdateReq14 performs a merge with any union data inside the FighterUpdateReq, using the provided FighterUpdateReq14
func (t *FighterUpdateReq) MergeFighterUpdateReq14(v FighterUpdateReq14) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsFighterUpdateReq15 returns the union data inside the FighterUpdateReq as a FighterUpdateReq15
func (t FighterUpdateReq) AsFighterUpdateReq15() (FighterUpdateReq15, error) {
	var body FighterUpdateReq15
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromFighterUpdateReq15 overwrites any union data inside the FighterUpdateReq as the provided FighterUpdateReq15
func (t *FighterUpdateReq) FromFighterUpdateReq15(v FighterUpdateReq15) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeFighterUpdateReq15 performs a merge with any union data inside the FighterUpdateReq, using the provided FighterUpdateReq15
func (t *FighterUpdateReq) MergeFighterUpdateReq15(v FighterUpdateReq15) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsFighterUpdateReq16 returns the union data inside the FighterUpdateReq as a FighterUpdateReq16
func (t FighterUpdateReq) AsFighterUpdateReq16() (FighterUpdateReq16, error) {
	var body FighterUpdateReq16
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromFighterUpdateReq16 overwrites any union data inside the FighterUpdateReq as the provided FighterUpdateReq16
func (t *FighterUpdateReq) FromFighterUpdateReq16(v FighterUpdateReq16) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeFighterUpdateReq16 performs a merge with any union data inside the FighterUpdateReq, using the provided FighterUpdateReq16
func (t *FighterUpdateReq) MergeFighterUpdateReq16(v FighterUpdateReq16) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t FighterUpdateReq) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	if err != nil {
		return nil, err
	}
	object := make(map[string]json.RawMessage)
	if t.union != nil {
		err = json.Unmarshal(b, &object)
		if err != nil {
			return nil, err
		}
	}

	if t.Bio != nil {
		object["bio"], err = json.Marshal(t.Bio)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'bio': %w", err)
		}
	}

	if t.Country != nil {
		object["country"], err = json.Marshal(t.Country)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'country': %w", err)
		}
	}

	if t.Disqualifications != nil {
		object["disqualifications"], err = json.Marshal(t.Disqualifications)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'disqualifications': %w", err)
		}
	}

	if t.Dob != nil {
		object["dob"], err = json.Marshal(t.Dob)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'dob': %w", err)
		}
	}

	if t.Draws != nil {
		object["draws"], err = json.Marshal(t.Draws)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'draws': %w", err)
		}
	}

	if t.FightingOutOf != nil {
		object["fighting_out_of"], err = json.Marshal(t.FightingOutOf)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'fighting_out_of': %w", err)
		}
	}

	if t.FirstName != nil {
		object["first_name"], err = json.Marshal(t.FirstName)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'first_name': %w", err)
		}
	}

	if t.Gender != nil {
		object["gender"], err = json.Marshal(t.Gender)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'gender': %w", err)
		}
	}

	if t.Height != nil {
		object["height"], err = json.Marshal(t.Height)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'height': %w", err)
		}
	}

	if t.LastName != nil {
		object["last_name"], err = json.Marshal(t.LastName)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'last_name': %w", err)
		}
	}

	if t.Losses != nil {
		object["losses"], err = json.Marshal(t.Losses)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'losses': %w", err)
		}
	}

	if t.Nickname != nil {
		object["nickname"], err = json.Marshal(t.Nickname)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'nickname': %w", err)
		}
	}

	if t.NoContests != nil {
		object["no_contests"], err = json.Marshal(t.NoContests)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'no_contests': %w", err)
		}
	}

	if t.Reach != nil {
		object["reach"], err = json.Marshal(t.Reach)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'reach': %w", err)
		}
	}

	if t.Stance != nil {
		object["stance"], err = json.Marshal(t.Stance)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'stance': %w", err)
		}
	}

	if t.Weight != nil {
		object["weight"], err = json.Marshal(t.Weight)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'weight': %w", err)
		}
	}

	if t.Wins != nil {
		object["wins"], err = json.Marshal(t.Wins)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'wins': %w", err)
		}
	}
	b, err = json.Marshal(object)
	return b, err
}

func (t *FighterUpdateReq) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	if err != nil {
		return err
	}
	object := make(map[string]json.RawMessage)
	err = json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["bio"]; found {
		err = json.Unmarshal(raw, &t.Bio)
		if err != nil {
			return fmt.Errorf("error reading 'bio': %w", err)
		}
	}

	if raw, found := object["country"]; found {
		err = json.Unmarshal(raw, &t.Country)
		if err != nil {
			return fmt.Errorf("error reading 'country': %w", err)
		}
	}

	if raw, found := object["disqualifications"]; found {
		err = json.Unmarshal(raw, &t.Disqualifications)
		if err != nil {
			return fmt.Errorf("error reading 'disqualifications': %w", err)
		}
	}

	if raw, found := object["dob"]; found {
		err = json.Unmarshal(raw, &t.Dob)
		if err != nil {
			return fmt.Errorf("error reading 'dob': %w", err)
		}
	}

	if raw, found := object["draws"]; found {
		err = json.Unmarshal(raw, &t.Draws)
		if err != nil {
			return fmt.Errorf("error reading 'draws': %w", err)
		}
	}

	if raw, found := object["fighting_out_of"]; found {
		err = json.Unmarshal(raw, &t.FightingOutOf)
		if err != nil {
			return fmt.Errorf("error reading 'fighting_out_of': %w", err)
		}
	}

	if raw, found := object["first_name"]; found {
		err = json.Unmarshal(raw, &t.FirstName)
		if err != nil {
			return fmt.Errorf("error reading 'first_name': %w", err)
		}
	}

	if raw, found := object["gender"]; found {
		err = json.Unmarshal(raw, &t.Gender)
		if err != nil {
			return fmt.Errorf("error reading 'gender': %w", err)
		}
	}

	if raw, found := object["height"]; found {
		err = json.Unmarshal(raw, &t.Height)
		if err != nil {
			return fmt.Errorf("error reading 'height': %w", err)
		}
	}

	if raw, found := object["last_name"]; found {
		err = json.Unmarshal(raw, &t.LastName)
		if err != nil {
			return fmt.Errorf("error reading 'last_name': %w", err)
		}
	}

	if raw, found := object["losses"]; found {
		err = json.Unmarshal(raw, &t.Losses)
		if err != nil {
			return fmt.Errorf("error reading 'losses': %w", err)
		}
	}

	if raw, found := object["nickname"]; found {
		err = json.Unmarshal(raw, &t.Nickname)
		if err != nil {
			return fmt.Errorf("error reading 'nickname': %w", err)
		}
	}

	if raw, found := object["no_contests"]; found {
		err = json.Unmarshal(raw, &t.NoContests)
		if err != nil {
			return fmt.Errorf("error reading 'no_contests': %w", err)
		}
	}

	if raw, found := object["reach"]; found {
		err = json.Unmarshal(raw, &t.Reach)
		if err != nil {
			return fmt.Errorf("error reading 'reach': %w", err)
		}
	}

	if raw, found := object["stance"]; found {
		err = json.Unmarshal(raw, &t.Stance)
		if err != nil {
			return fmt.Errorf("error reading 'stance': %w", err)
		}
	}

	if raw, found := object["weight"]; found {
		err = json.Unmarshal(raw, &t.Weight)
		if err != nil {
			return fmt.Errorf("error reading 'weight': %w", err)
		}
	}

	if raw, found := object["wins"]; found {
		err = json.Unmarshal(raw, &t.Wins)
		if err != nil {
			return fmt.Errorf("error reading 'wins': %w", err)
		}
	}

	return err
}

// AsUserUpdateReq0 returns the union data inside the UserUpdateReq as a UserUpdateReq0
func (t UserUpdateReq) AsUserUpdateReq0() (UserUpdateReq0, error) {
	var body UserUpdateReq0
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromUserUpdateReq0 overwrites any union data inside the UserUpdateReq as the provided UserUpdateReq0
func (t *UserUpdateReq) FromUserUpdateReq0(v UserUpdateReq0) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeUserUpdateReq0 performs a merge with any union data inside the UserUpdateReq, using the provided UserUpdateReq0
func (t *UserUpdateReq) MergeUserUpdateReq0(v UserUpdateReq0) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsUserUpdateReq1 returns the union data inside the UserUpdateReq as a UserUpdateReq1
func (t UserUpdateReq) AsUserUpdateReq1() (UserUpdateReq1, error) {
	var body UserUpdateReq1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromUserUpdateReq1 overwrites any union data inside the UserUpdateReq as the provided UserUpdateReq1
func (t *UserUpdateReq) FromUserUpdateReq1(v UserUpdateReq1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeUserUpdateReq1 performs a merge with any union data inside the UserUpdateReq, using the provided UserUpdateReq1
func (t *UserUpdateReq) MergeUserUpdateReq1(v UserUpdateReq1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsUserUpdateReq2 returns the union data inside the UserUpdateReq as a UserUpdateReq2
func (t UserUpdateReq) AsUserUpdateReq2() (UserUpdateReq2, error) {
	var body UserUpdateReq2
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromUserUpdateReq2 overwrites any union data inside the UserUpdateReq as the provided UserUpdateReq2
func (t *UserUpdateReq) FromUserUpdateReq2(v UserUpdateReq2) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeUserUpdateReq2 performs a merge with any union data inside the UserUpdateReq, using the provided UserUpdateReq2
func (t *UserUpdateReq) MergeUserUpdateReq2(v UserUpdateReq2) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsUserUpdateReq3 returns the union data inside the UserUpdateReq as a UserUpdateReq3
func (t UserUpdateReq) AsUserUpdateReq3() (UserUpdateReq3, error) {
	var body UserUpdateReq3
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromUserUpdateReq3 overwrites any union data inside the UserUpdateReq as the provided UserUpdateReq3
func (t *UserUpdateReq) FromUserUpdateReq3(v UserUpdateReq3) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeUserUpdateReq3 performs a merge with any union data inside the UserUpdateReq, using the provided UserUpdateReq3
func (t *UserUpdateReq) MergeUserUpdateReq3(v UserUpdateReq3) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsUserUpdateReq4 returns the union data inside the UserUpdateReq as a UserUpdateReq4
func (t UserUpdateReq) AsUserUpdateReq4() (UserUpdateReq4, error) {
	var body UserUpdateReq4
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromUserUpdateReq4 overwrites any union data inside the UserUpdateReq as the provided UserUpdateReq4
func (t *UserUpdateReq) FromUserUpdateReq4(v UserUpdateReq4) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeUserUpdateReq4 performs a merge with any union data inside the UserUpdateReq, using the provided UserUpdateReq4
func (t *UserUpdateReq) MergeUserUpdateReq4(v UserUpdateReq4) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsUserUpdateReq5 returns the union data inside the UserUpdateReq as a UserUpdateReq5
func (t UserUpdateReq) AsUserUpdateReq5() (UserUpdateReq5, error) {
	var body UserUpdateReq5
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromUserUpdateReq5 overwrites any union data inside the UserUpdateReq as the provided UserUpdateReq5
func (t *UserUpdateReq) FromUserUpdateReq5(v UserUpdateReq5) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeUserUpdateReq5 performs a merge with any union data inside the UserUpdateReq, using the provided UserUpdateReq5
func (t *UserUpdateReq) MergeUserUpdateReq5(v UserUpdateReq5) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsUserUpdateReq6 returns the union data inside the UserUpdateReq as a UserUpdateReq6
func (t UserUpdateReq) AsUserUpdateReq6() (UserUpdateReq6, error) {
	var body UserUpdateReq6
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromUserUpdateReq6 overwrites any union data inside the UserUpdateReq as the provided UserUpdateReq6
func (t *UserUpdateReq) FromUserUpdateReq6(v UserUpdateReq6) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeUserUpdateReq6 performs a merge with any union data inside the UserUpdateReq, using the provided UserUpdateReq6
func (t *UserUpdateReq) MergeUserUpdateReq6(v UserUpdateReq6) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsUserUpdateReq7 returns the union data inside the UserUpdateReq as a UserUpdateReq7
func (t UserUpdateReq) AsUserUpdateReq7() (UserUpdateReq7, error) {
	var body UserUpdateReq7
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromUserUpdateReq7 overwrites any union data inside the UserUpdateReq as the provided UserUpdateReq7
func (t *UserUpdateReq) FromUserUpdateReq7(v UserUpdateReq7) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeUserUpdateReq7 performs a merge with any union data inside the UserUpdateReq, using the provided UserUpdateReq7
func (t *UserUpdateReq) MergeUserUpdateReq7(v UserUpdateReq7) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t UserUpdateReq) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	if err != nil {
		return nil, err
	}
	object := make(map[string]json.RawMessage)
	if t.union != nil {
		err = json.Unmarshal(b, &object)
		if err != nil {
			return nil, err
		}
	}

	if t.Bio != nil {
		object["bio"], err = json.Marshal(t.Bio)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'bio': %w", err)
		}
	}

	if t.Dob != nil {
		object["dob"], err = json.Marshal(t.Dob)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'dob': %w", err)
		}
	}

	if t.Email != nil {
		object["email"], err = json.Marshal(t.Email)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'email': %w", err)
		}
	}

	if t.FirstName != nil {
		object["first_name"], err = json.Marshal(t.FirstName)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'first_name': %w", err)
		}
	}

	if t.Gender != nil {
		object["gender"], err = json.Marshal(t.Gender)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'gender': %w", err)
		}
	}

	if t.LastName != nil {
		object["last_name"], err = json.Marshal(t.LastName)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'last_name': %w", err)
		}
	}

	if t.Location != nil {
		object["location"], err = json.Marshal(t.Location)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'location': %w", err)
		}
	}

	if t.Password != nil {
		object["password"], err = json.Marshal(t.Password)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'password': %w", err)
		}
	}

	if t.Username != nil {
		object["username"], err = json.Marshal(t.Username)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'username': %w", err)
		}
	}
	b, err = json.Marshal(object)
	return b, err
}

func (t *UserUpdateReq) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	if err != nil {
		return err
	}
	object := make(map[string]json.RawMessage)
	err = json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["bio"]; found {
		err = json.Unmarshal(raw, &t.Bio)
		if err != nil {
			return fmt.Errorf("error reading 'bio': %w", err)
		}
	}

	if raw, found := object["dob"]; found {
		err = json.Unmarshal(raw, &t.Dob)
		if err != nil {
			return fmt.Errorf("error reading 'dob': %w", err)
		}
	}

	if raw, found := object["email"]; found {
		err = json.Unmarshal(raw, &t.Email)
		if err != nil {
			return fmt.Errorf("error reading 'email': %w", err)
		}
	}

	if raw, found := object["first_name"]; found {
		err = json.Unmarshal(raw, &t.FirstName)
		if err != nil {
			return fmt.Errorf("error reading 'first_name': %w", err)
		}
	}

	if raw, found := object["gender"]; found {
		err = json.Unmarshal(raw, &t.Gender)
		if err != nil {
			return fmt.Errorf("error reading 'gender': %w", err)
		}
	}

	if raw, found := object["last_name"]; found {
		err = json.Unmarshal(raw, &t.LastName)
		if err != nil {
			return fmt.Errorf("error reading 'last_name': %w", err)
		}
	}

	if raw, found := object["location"]; found {
		err = json.Unmarshal(raw, &t.Location)
		if err != nil {
			return fmt.Errorf("error reading 'location': %w", err)
		}
	}

	if raw, found := object["password"]; found {
		err = json.Unmarshal(raw, &t.Password)
		if err != nil {
			return fmt.Errorf("error reading 'password': %w", err)
		}
	}

	if raw, found := object["username"]; found {
		err = json.Unmarshal(raw, &t.Username)
		if err != nil {
			return fmt.Errorf("error reading 'username': %w", err)
		}
	}

	return err
}
