// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package postgres

import (
	"database/sql/driver"
	"fmt"

	uuid "github.com/gofrs/uuid/v5"
	"github.com/jackc/pgx/v5/pgtype"
)

type CardStage string

const (
	CardStageEarlyPrelims CardStage = "early_prelims"
	CardStagePrelims      CardStage = "prelims"
	CardStageMain         CardStage = "main"
)

func (e *CardStage) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CardStage(s)
	case string:
		*e = CardStage(s)
	default:
		return fmt.Errorf("unsupported scan type for CardStage: %T", src)
	}
	return nil
}

type NullCardStage struct {
	CardStage CardStage
	Valid     bool // Valid is true if CardStage is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCardStage) Scan(value interface{}) error {
	if value == nil {
		ns.CardStage, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CardStage.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCardStage) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.CardStage), nil
}

type Corner string

const (
	CornerRed  Corner = "red"
	CornerBlue Corner = "blue"
)

func (e *Corner) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = Corner(s)
	case string:
		*e = Corner(s)
	default:
		return fmt.Errorf("unsupported scan type for Corner: %T", src)
	}
	return nil
}

type NullCorner struct {
	Corner Corner
	Valid  bool // Valid is true if Corner is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCorner) Scan(value interface{}) error {
	if value == nil {
		ns.Corner, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.Corner.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCorner) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.Corner), nil
}

type FightStatus string

const (
	FightStatusScheduled  FightStatus = "scheduled"
	FightStatusInProgress FightStatus = "in_progress"
	FightStatusCompleted  FightStatus = "completed"
	FightStatusCancelled  FightStatus = "cancelled"
)

func (e *FightStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = FightStatus(s)
	case string:
		*e = FightStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for FightStatus: %T", src)
	}
	return nil
}

type NullFightStatus struct {
	FightStatus FightStatus
	Valid       bool // Valid is true if FightStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullFightStatus) Scan(value interface{}) error {
	if value == nil {
		ns.FightStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.FightStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullFightStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.FightStatus), nil
}

type Gender string

const (
	GenderMale   Gender = "male"
	GenderFemale Gender = "female"
	GenderOther  Gender = "other"
)

func (e *Gender) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = Gender(s)
	case string:
		*e = Gender(s)
	default:
		return fmt.Errorf("unsupported scan type for Gender: %T", src)
	}
	return nil
}

type NullGender struct {
	Gender Gender
	Valid  bool // Valid is true if Gender is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullGender) Scan(value interface{}) error {
	if value == nil {
		ns.Gender, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.Gender.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullGender) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.Gender), nil
}

type ResourceType string

const (
	ResourceTypeUsers    ResourceType = "users"
	ResourceTypeFighters ResourceType = "fighters"
	ResourceTypeCards    ResourceType = "cards"
	ResourceTypeFights   ResourceType = "fights"
	ResourceTypePicks    ResourceType = "picks"
)

func (e *ResourceType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ResourceType(s)
	case string:
		*e = ResourceType(s)
	default:
		return fmt.Errorf("unsupported scan type for ResourceType: %T", src)
	}
	return nil
}

type NullResourceType struct {
	ResourceType ResourceType
	Valid        bool // Valid is true if ResourceType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullResourceType) Scan(value interface{}) error {
	if value == nil {
		ns.ResourceType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ResourceType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullResourceType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ResourceType), nil
}

type WinMethod string

const (
	WinMethodKo  WinMethod = "ko"
	WinMethodTko WinMethod = "tko"
	WinMethodDq  WinMethod = "dq"
	WinMethodSub WinMethod = "sub"
	WinMethodUd  WinMethod = "ud"
	WinMethodSd  WinMethod = "sd"
	WinMethodMd  WinMethod = "md"
)

func (e *WinMethod) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = WinMethod(s)
	case string:
		*e = WinMethod(s)
	default:
		return fmt.Errorf("unsupported scan type for WinMethod: %T", src)
	}
	return nil
}

type NullWinMethod struct {
	WinMethod WinMethod
	Valid     bool // Valid is true if WinMethod is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullWinMethod) Scan(value interface{}) error {
	if value == nil {
		ns.WinMethod, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.WinMethod.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullWinMethod) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.WinMethod), nil
}

type Card struct {
	ID        uuid.UUID
	Name      string
	Location  string
	Date      pgtype.Timestamptz
	Promotion string
	CreatedAt pgtype.Timestamptz
	CreatedBy pgtype.UUID
	UpdatedAt pgtype.Timestamptz
	UpdatedBy pgtype.UUID
}

type CardFight struct {
	ID          uuid.UUID
	CardID      uuid.UUID
	FightID     uuid.UUID
	Stage       CardStage
	OrderInCard int32
	CreatedAt   pgtype.Timestamptz
	CreatedBy   pgtype.UUID
	UpdatedAt   pgtype.Timestamptz
	UpdatedBy   pgtype.UUID
}

type Fight struct {
	ID             uuid.UUID
	Date           pgtype.Timestamptz
	NoOfRounds     int32
	WeightClass    string
	IsChampionship bool
	Status         FightStatus
	Referee        pgtype.Text
	Location       pgtype.Text
	CreatedAt      pgtype.Timestamptz
	CreatedBy      pgtype.UUID
	UpdatedAt      pgtype.Timestamptz
	UpdatedBy      pgtype.UUID
}

type FightParticipant struct {
	ID        uuid.UUID
	FightID   uuid.UUID
	FighterID uuid.UUID
	Corner    Corner
	CreatedAt pgtype.Timestamptz
	CreatedBy pgtype.UUID
	UpdatedAt pgtype.Timestamptz
	UpdatedBy pgtype.UUID
}

type FightResult struct {
	ID              uuid.UUID
	FightID         uuid.UUID
	IsDraw          bool
	IsNoContest     bool
	WinnerID        pgtype.UUID
	Method          NullWinMethod
	Round           pgtype.Int4
	FightTime       pgtype.Interval
	JudgesScorecard []byte
	Referee         pgtype.Text
	FightOfTheNight bool
	CreatedAt       pgtype.Timestamptz
	CreatedBy       pgtype.UUID
	UpdatedAt       pgtype.Timestamptz
	UpdatedBy       pgtype.UUID
}

type Fighter struct {
	ID                uuid.UUID
	FirstName         string
	LastName          string
	Nickname          pgtype.Text
	Gender            Gender
	Dob               pgtype.Date
	Height            pgtype.Numeric
	Weight            pgtype.Numeric
	Reach             pgtype.Numeric
	Stance            string
	Country           string
	FightingOutOf     string
	Bio               pgtype.Text
	ProfilePicture    pgtype.Text
	Wins              int32
	Losses            int32
	Draws             int32
	Disqualifications int32
	NoContests        int32
	CreatedAt         pgtype.Timestamptz
	CreatedBy         pgtype.UUID
	UpdatedAt         pgtype.Timestamptz
	UpdatedBy         pgtype.UUID
}

type Follower struct {
	ID         uuid.UUID
	FollowerID uuid.UUID
	FolloweeID uuid.UUID
	CreatedAt  pgtype.Timestamptz
	CreatedBy  pgtype.UUID
}

type Permission struct {
	ID          uuid.UUID
	Name        string
	Version     string
	Resource    ResourceType
	Operation   string
	Description string
	CreatedAt   pgtype.Timestamptz
	CreatedBy   pgtype.UUID
	UpdatedAt   pgtype.Timestamptz
	UpdatedBy   pgtype.UUID
}

type Pick struct {
	ID                 uuid.UUID
	FightID            uuid.UUID
	UserID             uuid.UUID
	FightParticipantID uuid.UUID
	Method             NullWinMethod
	Round              pgtype.Int4
	CreatedAt          pgtype.Timestamptz
	CreatedBy          pgtype.UUID
	UpdatedAt          pgtype.Timestamptz
	UpdatedBy          pgtype.UUID
}

type RefreshToken struct {
	ID         uuid.UUID
	UserID     uuid.UUID
	TokenHash  string
	Jti        uuid.UUID
	ExpiresAt  pgtype.Timestamptz
	Revoked    bool
	ReplacedBy pgtype.UUID
	IpAddress  pgtype.Text
	UserAgent  pgtype.Text
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
}

type Role struct {
	ID          uuid.UUID
	Name        string
	Description string
	CreatedAt   pgtype.Timestamptz
	CreatedBy   pgtype.UUID
	UpdatedAt   pgtype.Timestamptz
	UpdatedBy   pgtype.UUID
}

type RolePermission struct {
	RoleID       uuid.UUID
	PermissionID uuid.UUID
	CreatedAt    pgtype.Timestamptz
	CreatedBy    pgtype.UUID
	UpdatedAt    pgtype.Timestamptz
	UpdatedBy    pgtype.UUID
}

type User struct {
	ID                              uuid.UUID
	Email                           string
	Username                        string
	FirstName                       string
	LastName                        string
	Dob                             pgtype.Date
	Gender                          Gender
	Location                        pgtype.Text
	Bio                             pgtype.Text
	ProfilePicture                  pgtype.Text
	PasswordHash                    string
	EmailVerified                   bool
	EmailVerificationTokenHash      []byte
	EmailVerificationTokenExpiresAt pgtype.Timestamptz
	LastLogin                       pgtype.Timestamptz
	CreatedAt                       pgtype.Timestamptz
	UpdatedAt                       pgtype.Timestamptz
	UpdatedBy                       pgtype.UUID
}

type UserRole struct {
	UserID    uuid.UUID
	RoleID    uuid.UUID
	CreatedAt pgtype.Timestamptz
	CreatedBy pgtype.UUID
	UpdatedAt pgtype.Timestamptz
	UpdatedBy pgtype.UUID
}
