// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package postgres

import (
	"context"

	uuid "github.com/gofrs/uuid/v5"
	"github.com/jackc/pgx/v5/pgtype"
)

const assignRoleToUserByRoleName = `-- name: AssignRoleToUserByRoleName :exec
INSERT INTO user_roles (user_id, role_id, created_at, created_by, updated_at, updated_by)
VALUES (
    $1,
    (SELECT id FROM roles WHERE name = $2),
    $3,
    $4,
    $5,
    $6
)
`

type AssignRoleToUserByRoleNameParams struct {
	UserID    uuid.UUID
	Name      string
	CreatedAt pgtype.Timestamptz
	CreatedBy pgtype.UUID
	UpdatedAt pgtype.Timestamptz
	UpdatedBy pgtype.UUID
}

func (q *Queries) AssignRoleToUserByRoleName(ctx context.Context, arg AssignRoleToUserByRoleNameParams) error {
	_, err := q.db.Exec(ctx, assignRoleToUserByRoleName,
		arg.UserID,
		arg.Name,
		arg.CreatedAt,
		arg.CreatedBy,
		arg.UpdatedAt,
		arg.UpdatedBy,
	)
	return err
}

const countFollowees = `-- name: CountFollowees :one
SELECT COUNT(*) AS followee_count
FROM followers
WHERE follower_id = $1
`

func (q *Queries) CountFollowees(ctx context.Context, followerID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countFollowees, followerID)
	var followee_count int64
	err := row.Scan(&followee_count)
	return followee_count, err
}

const countFollowers = `-- name: CountFollowers :one
SELECT COUNT(*) AS follower_count
FROM followers
WHERE followee_id = $1
`

func (q *Queries) CountFollowers(ctx context.Context, followeeID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countFollowers, followeeID)
	var follower_count int64
	err := row.Scan(&follower_count)
	return follower_count, err
}

const countUsers = `-- name: CountUsers :one
SELECT COUNT(*) AS user_count
FROM users
`

func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countUsers)
	var user_count int64
	err := row.Scan(&user_count)
	return user_count, err
}

const createFighter = `-- name: CreateFighter :exec
INSERT INTO fighters (
    id,
    first_name,
    last_name,
    nickname,
    gender,
    dob,
    height,
    weight,
    reach,
    stance,
    country,
    fighting_out_of,
    bio,
    profile_picture,
    wins,
    losses,
    draws,
    disqualifications,
    no_contests,
    created_at,
    created_by,
    updated_at,
    updated_by
) VALUES (
    $1, $2, $3, $4, $5,
    $6, $7, $8, $9, $10,
    $11, $12, $13, $14, $15,
    $16, $17, $18, $19, $20,
    $21, $22, $23
)
`

type CreateFighterParams struct {
	ID                uuid.UUID
	FirstName         string
	LastName          string
	Nickname          pgtype.Text
	Gender            Gender
	Dob               pgtype.Date
	Height            pgtype.Numeric
	Weight            pgtype.Numeric
	Reach             pgtype.Numeric
	Stance            string
	Country           string
	FightingOutOf     string
	Bio               pgtype.Text
	ProfilePicture    pgtype.Text
	Wins              int32
	Losses            int32
	Draws             int32
	Disqualifications int32
	NoContests        int32
	CreatedAt         pgtype.Timestamptz
	CreatedBy         pgtype.UUID
	UpdatedAt         pgtype.Timestamptz
	UpdatedBy         pgtype.UUID
}

func (q *Queries) CreateFighter(ctx context.Context, arg CreateFighterParams) error {
	_, err := q.db.Exec(ctx, createFighter,
		arg.ID,
		arg.FirstName,
		arg.LastName,
		arg.Nickname,
		arg.Gender,
		arg.Dob,
		arg.Height,
		arg.Weight,
		arg.Reach,
		arg.Stance,
		arg.Country,
		arg.FightingOutOf,
		arg.Bio,
		arg.ProfilePicture,
		arg.Wins,
		arg.Losses,
		arg.Draws,
		arg.Disqualifications,
		arg.NoContests,
		arg.CreatedAt,
		arg.CreatedBy,
		arg.UpdatedAt,
		arg.UpdatedBy,
	)
	return err
}

const createUser = `-- name: CreateUser :exec

INSERT INTO users (
    id,
    email,
    first_name,
    last_name,
    username,
    bio,
    profile_picture,
    location,
    password_hash,
    dob,
    gender,
    created_at,
    updated_at,
    updated_by
) VALUES (
    $1, $2, $3, $4, $5,
    $6, $7, $8, $9, $10,
    $11, $12, $13, $14
)
`

type CreateUserParams struct {
	ID             uuid.UUID
	Email          string
	FirstName      string
	LastName       string
	Username       string
	Bio            pgtype.Text
	ProfilePicture pgtype.Text
	Location       pgtype.Text
	PasswordHash   string
	Dob            pgtype.Date
	Gender         Gender
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
	UpdatedBy      pgtype.UUID
}

// -----------------------------------
// SQL queries for user management --
// -----------------------------------
func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.Exec(ctx, createUser,
		arg.ID,
		arg.Email,
		arg.FirstName,
		arg.LastName,
		arg.Username,
		arg.Bio,
		arg.ProfilePicture,
		arg.Location,
		arg.PasswordHash,
		arg.Dob,
		arg.Gender,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.UpdatedBy,
	)
	return err
}

const deleteUserByID = `-- name: DeleteUserByID :exec
DELETE FROM users
WHERE id = $1
`

func (q *Queries) DeleteUserByID(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteUserByID, id)
	return err
}

const followUser = `-- name: FollowUser :exec
INSERT INTO followers (id, follower_id, followee_id, created_at, created_by)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (follower_id, followee_id) DO NOTHING
`

type FollowUserParams struct {
	ID         uuid.UUID
	FollowerID uuid.UUID
	FolloweeID uuid.UUID
	CreatedAt  pgtype.Timestamptz
	CreatedBy  pgtype.UUID
}

func (q *Queries) FollowUser(ctx context.Context, arg FollowUserParams) error {
	_, err := q.db.Exec(ctx, followUser,
		arg.ID,
		arg.FollowerID,
		arg.FolloweeID,
		arg.CreatedAt,
		arg.CreatedBy,
	)
	return err
}

const getFighterByID = `-- name: GetFighterByID :one

SELECT
    id,
    first_name,
    last_name,
    nickname,
    gender,
    dob,
    height,
    weight,
    reach,
    stance,
    country,
    fighting_out_of,
    bio,
    profile_picture,
    wins,
    losses,
    draws,
    disqualifications,
    no_contests,
    created_at,
    created_by,
    updated_at,
    updated_by
FROM fighters
WHERE id = $1
`

// --------------------------------------
// SQL queries for fighter management --
// --------------------------------------
func (q *Queries) GetFighterByID(ctx context.Context, id uuid.UUID) (Fighter, error) {
	row := q.db.QueryRow(ctx, getFighterByID, id)
	var i Fighter
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.Nickname,
		&i.Gender,
		&i.Dob,
		&i.Height,
		&i.Weight,
		&i.Reach,
		&i.Stance,
		&i.Country,
		&i.FightingOutOf,
		&i.Bio,
		&i.ProfilePicture,
		&i.Wins,
		&i.Losses,
		&i.Draws,
		&i.Disqualifications,
		&i.NoContests,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}

const getRefreshTokenByHash = `-- name: GetRefreshTokenByHash :one
SELECT id, user_id, token_hash, jti, expires_at, revoked, replaced_by, ip_address, user_agent, created_at, updated_at
FROM refresh_tokens
WHERE token_hash = $1
`

func (q *Queries) GetRefreshTokenByHash(ctx context.Context, tokenHash string) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, getRefreshTokenByHash, tokenHash)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.Jti,
		&i.ExpiresAt,
		&i.Revoked,
		&i.ReplacedBy,
		&i.IpAddress,
		&i.UserAgent,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT
    id,
    email,
    first_name,
    last_name,
    username,
    bio,
    profile_picture,
    location,
    password_hash,
    dob,
    gender,
    created_at,
    updated_at,
    updated_by
FROM users
WHERE email = $1
`

type GetUserByEmailRow struct {
	ID             uuid.UUID
	Email          string
	FirstName      string
	LastName       string
	Username       string
	Bio            pgtype.Text
	ProfilePicture pgtype.Text
	Location       pgtype.Text
	PasswordHash   string
	Dob            pgtype.Date
	Gender         Gender
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
	UpdatedBy      pgtype.UUID
}

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i GetUserByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.Username,
		&i.Bio,
		&i.ProfilePicture,
		&i.Location,
		&i.PasswordHash,
		&i.Dob,
		&i.Gender,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT
    id,
    email,
    first_name,
    last_name,
    username,
    bio,
    profile_picture,
    location,
    password_hash,
    dob,
    gender,
    created_at,
    updated_at,
    updated_by
FROM users
WHERE id = $1
`

type GetUserByIDRow struct {
	ID             uuid.UUID
	Email          string
	FirstName      string
	LastName       string
	Username       string
	Bio            pgtype.Text
	ProfilePicture pgtype.Text
	Location       pgtype.Text
	PasswordHash   string
	Dob            pgtype.Date
	Gender         Gender
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
	UpdatedBy      pgtype.UUID
}

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (GetUserByIDRow, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i GetUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.Username,
		&i.Bio,
		&i.ProfilePicture,
		&i.Location,
		&i.PasswordHash,
		&i.Dob,
		&i.Gender,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT
    id,
    email,
    first_name,
    last_name,
    username,
    bio,
    profile_picture,
    location,
    password_hash,
    dob,
    gender,
    created_at,
    updated_at,
    updated_by
FROM users
WHERE username = $1
`

type GetUserByUsernameRow struct {
	ID             uuid.UUID
	Email          string
	FirstName      string
	LastName       string
	Username       string
	Bio            pgtype.Text
	ProfilePicture pgtype.Text
	Location       pgtype.Text
	PasswordHash   string
	Dob            pgtype.Date
	Gender         Gender
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
	UpdatedBy      pgtype.UUID
}

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (GetUserByUsernameRow, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, username)
	var i GetUserByUsernameRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.FirstName,
		&i.LastName,
		&i.Username,
		&i.Bio,
		&i.ProfilePicture,
		&i.Location,
		&i.PasswordHash,
		&i.Dob,
		&i.Gender,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}

const getUserPermissionsAndRolesByID = `-- name: GetUserPermissionsAndRolesByID :many
SELECT
    r.name AS role_name,
    p.name AS permission_name,
    p.resource,
    p.version,
    p.operation
FROM users u
JOIN user_roles ur ON ur.user_id = u.id
JOIN roles r ON r.id = ur.role_id
JOIN role_permissions rp ON rp.role_id = r.id
JOIN permissions p ON p.id = rp.permission_id
WHERE u.id = $1
ORDER BY r.name, p.resource, p.name
`

type GetUserPermissionsAndRolesByIDRow struct {
	RoleName       string
	PermissionName string
	Resource       ResourceType
	Version        string
	Operation      string
}

func (q *Queries) GetUserPermissionsAndRolesByID(ctx context.Context, id uuid.UUID) ([]GetUserPermissionsAndRolesByIDRow, error) {
	rows, err := q.db.Query(ctx, getUserPermissionsAndRolesByID, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserPermissionsAndRolesByIDRow
	for rows.Next() {
		var i GetUserPermissionsAndRolesByIDRow
		if err := rows.Scan(
			&i.RoleName,
			&i.PermissionName,
			&i.Resource,
			&i.Version,
			&i.Operation,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserPermissionsByID = `-- name: GetUserPermissionsByID :many
SELECT p.name, p.resource, p.version, p.operation
FROM users u
JOIN user_roles ur ON ur.user_id = u.id
JOIN roles r ON r.id = ur.role_id
JOIN role_permissions rp ON rp.role_id = r.id
JOIN permissions p ON p.id = rp.permission_id
WHERE u.id = $1
ORDER BY p.resource, p.name
`

type GetUserPermissionsByIDRow struct {
	Name      string
	Resource  ResourceType
	Version   string
	Operation string
}

func (q *Queries) GetUserPermissionsByID(ctx context.Context, id uuid.UUID) ([]GetUserPermissionsByIDRow, error) {
	rows, err := q.db.Query(ctx, getUserPermissionsByID, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserPermissionsByIDRow
	for rows.Next() {
		var i GetUserPermissionsByIDRow
		if err := rows.Scan(
			&i.Name,
			&i.Resource,
			&i.Version,
			&i.Operation,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserRBAC = `-- name: GetUserRBAC :one
SELECT
    u.id AS user_id,
    json_agg(DISTINCT r.name) AS roles,
    json_agg(
        DISTINCT jsonb_build_object(
            'id', p.id,
            'name', p.name,
            'resource', p.resource,
            'version', p.version,
            'operation', p.operation
        )
    ) AS permissions
FROM users u
JOIN user_roles ur            ON ur.user_id = u.id
JOIN roles r                  ON r.id = ur.role_id
JOIN role_permissions rp      ON rp.role_id = r.id
JOIN permissions p            ON p.id = rp.permission_id
WHERE u.id = $1
GROUP BY u.id
`

type GetUserRBACRow struct {
	UserID      uuid.UUID
	Roles       []byte
	Permissions []byte
}

func (q *Queries) GetUserRBAC(ctx context.Context, id uuid.UUID) (GetUserRBACRow, error) {
	row := q.db.QueryRow(ctx, getUserRBAC, id)
	var i GetUserRBACRow
	err := row.Scan(&i.UserID, &i.Roles, &i.Permissions)
	return i, err
}

const getUserRolesByID = `-- name: GetUserRolesByID :many
SELECT r.name
FROM roles r
JOIN user_roles ur ON ur.role_id = r.id
WHERE ur.user_id = $1
ORDER BY r.name
`

func (q *Queries) GetUserRolesByID(ctx context.Context, userID uuid.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, getUserRolesByID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const isFollowing = `-- name: IsFollowing :one
SELECT EXISTS (
  SELECT 1
  FROM followers
  WHERE follower_id = $1 AND followee_id = $2
) AS is_following
`

type IsFollowingParams struct {
	FollowerID uuid.UUID
	FolloweeID uuid.UUID
}

func (q *Queries) IsFollowing(ctx context.Context, arg IsFollowingParams) (bool, error) {
	row := q.db.QueryRow(ctx, isFollowing, arg.FollowerID, arg.FolloweeID)
	var is_following bool
	err := row.Scan(&is_following)
	return is_following, err
}

const isUserEmailVerifiedByID = `-- name: IsUserEmailVerifiedByID :one
SELECT email_verified
FROM users
WHERE id = $1
`

func (q *Queries) IsUserEmailVerifiedByID(ctx context.Context, id uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, isUserEmailVerifiedByID, id)
	var email_verified bool
	err := row.Scan(&email_verified)
	return email_verified, err
}

const listFollowees = `-- name: ListFollowees :many
SELECT
  u.id, u.email, u.first_name, u.last_name, u.username,
  u.bio, u.profile_picture, u.location, u.dob, u.gender,
  u.created_at, u.updated_at, u.updated_by
FROM followers f
JOIN users u ON u.id = f.followee_id
WHERE f.follower_id = $1
  AND f.id < $2
ORDER BY f.id DESC
LIMIT $3
`

type ListFolloweesParams struct {
	FollowerID uuid.UUID
	ID         uuid.UUID
	Limit      int32
}

type ListFolloweesRow struct {
	ID             uuid.UUID
	Email          string
	FirstName      string
	LastName       string
	Username       string
	Bio            pgtype.Text
	ProfilePicture pgtype.Text
	Location       pgtype.Text
	Dob            pgtype.Date
	Gender         Gender
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
	UpdatedBy      pgtype.UUID
}

// for first page (i.e. empty last_seen_id) the app passes sentinel max value for UUID7
func (q *Queries) ListFollowees(ctx context.Context, arg ListFolloweesParams) ([]ListFolloweesRow, error) {
	rows, err := q.db.Query(ctx, listFollowees, arg.FollowerID, arg.ID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFolloweesRow
	for rows.Next() {
		var i ListFolloweesRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.FirstName,
			&i.LastName,
			&i.Username,
			&i.Bio,
			&i.ProfilePicture,
			&i.Location,
			&i.Dob,
			&i.Gender,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UpdatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFollowers = `-- name: ListFollowers :many
SELECT
  u.id, u.email, u.first_name, u.last_name, u.username,
  u.bio, u.profile_picture, u.location, u.dob, u.gender,
  u.created_at, u.updated_at, u.updated_by
FROM followers f
JOIN users u ON u.id = f.follower_id
WHERE f.followee_id = $1
  AND f.id < $2
ORDER BY f.id DESC
LIMIT $3
`

type ListFollowersParams struct {
	FolloweeID uuid.UUID
	ID         uuid.UUID
	Limit      int32
}

type ListFollowersRow struct {
	ID             uuid.UUID
	Email          string
	FirstName      string
	LastName       string
	Username       string
	Bio            pgtype.Text
	ProfilePicture pgtype.Text
	Location       pgtype.Text
	Dob            pgtype.Date
	Gender         Gender
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
	UpdatedBy      pgtype.UUID
}

// for first page (i.e. empty last_seen_id) the app passes sentinel max value for UUID7
func (q *Queries) ListFollowers(ctx context.Context, arg ListFollowersParams) ([]ListFollowersRow, error) {
	rows, err := q.db.Query(ctx, listFollowers, arg.FolloweeID, arg.ID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFollowersRow
	for rows.Next() {
		var i ListFollowersRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.FirstName,
			&i.LastName,
			&i.Username,
			&i.Bio,
			&i.ProfilePicture,
			&i.Location,
			&i.Dob,
			&i.Gender,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UpdatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsers = `-- name: ListUsers :many
SELECT
    id,
    email,
    first_name,
    last_name,
    username,
    bio,
    profile_picture,
    location,
    dob,
    gender,
    created_at,
    updated_at,
    updated_by
FROM users
WHERE id > $1
ORDER BY id
LIMIT $2
`

type ListUsersParams struct {
	ID    uuid.UUID
	Limit int32
}

type ListUsersRow struct {
	ID             uuid.UUID
	Email          string
	FirstName      string
	LastName       string
	Username       string
	Bio            pgtype.Text
	ProfilePicture pgtype.Text
	Location       pgtype.Text
	Dob            pgtype.Date
	Gender         Gender
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
	UpdatedBy      pgtype.UUID
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]ListUsersRow, error) {
	rows, err := q.db.Query(ctx, listUsers, arg.ID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUsersRow
	for rows.Next() {
		var i ListUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.FirstName,
			&i.LastName,
			&i.Username,
			&i.Bio,
			&i.ProfilePicture,
			&i.Location,
			&i.Dob,
			&i.Gender,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UpdatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeAndRotateRefreshTokenByHash = `-- name: RevokeAndRotateRefreshTokenByHash :exec
UPDATE refresh_tokens SET
    revoked = TRUE,
    replaced_by = $2,
    updated_at = $3
WHERE token_hash = $1
`

type RevokeAndRotateRefreshTokenByHashParams struct {
	TokenHash  string
	ReplacedBy pgtype.UUID
	UpdatedAt  pgtype.Timestamptz
}

func (q *Queries) RevokeAndRotateRefreshTokenByHash(ctx context.Context, arg RevokeAndRotateRefreshTokenByHashParams) error {
	_, err := q.db.Exec(ctx, revokeAndRotateRefreshTokenByHash, arg.TokenHash, arg.ReplacedBy, arg.UpdatedAt)
	return err
}

const revokeRefreshTokenByHash = `-- name: RevokeRefreshTokenByHash :exec
UPDATE refresh_tokens SET
    revoked = TRUE,
    updated_at = $2
WHERE token_hash = $1
`

type RevokeRefreshTokenByHashParams struct {
	TokenHash string
	UpdatedAt pgtype.Timestamptz
}

func (q *Queries) RevokeRefreshTokenByHash(ctx context.Context, arg RevokeRefreshTokenByHashParams) error {
	_, err := q.db.Exec(ctx, revokeRefreshTokenByHash, arg.TokenHash, arg.UpdatedAt)
	return err
}

const storeRefreshToken = `-- name: StoreRefreshToken :exec

INSERT INTO refresh_tokens (
    id,
    user_id,
    token_hash,
    jti,
    expires_at,
    ip_address,
    user_agent,
    created_at,
    updated_at
)
VALUES ($1,$2,$3,$4,$5,$6, $7, $8, $9)
`

type StoreRefreshTokenParams struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	TokenHash string
	Jti       uuid.UUID
	ExpiresAt pgtype.Timestamptz
	IpAddress pgtype.Text
	UserAgent pgtype.Text
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

// -----------------------------------
// SQL queries for auth management --
// -----------------------------------
func (q *Queries) StoreRefreshToken(ctx context.Context, arg StoreRefreshTokenParams) error {
	_, err := q.db.Exec(ctx, storeRefreshToken,
		arg.ID,
		arg.UserID,
		arg.TokenHash,
		arg.Jti,
		arg.ExpiresAt,
		arg.IpAddress,
		arg.UserAgent,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const unfollowUser = `-- name: UnfollowUser :exec
DELETE FROM followers
WHERE follower_id = $1 AND followee_id = $2
`

type UnfollowUserParams struct {
	FollowerID uuid.UUID
	FolloweeID uuid.UUID
}

func (q *Queries) UnfollowUser(ctx context.Context, arg UnfollowUserParams) error {
	_, err := q.db.Exec(ctx, unfollowUser, arg.FollowerID, arg.FolloweeID)
	return err
}

const updateEmailVerificationTokenHashByUserID = `-- name: UpdateEmailVerificationTokenHashByUserID :exec
UPDATE users SET
    email_verification_token_hash = $2,
    email_verification_token_expires_at = $3,
    updated_at = $4
WHERE id = $1
`

type UpdateEmailVerificationTokenHashByUserIDParams struct {
	ID                              uuid.UUID
	EmailVerificationTokenHash      []byte
	EmailVerificationTokenExpiresAt pgtype.Timestamptz
	UpdatedAt                       pgtype.Timestamptz
}

func (q *Queries) UpdateEmailVerificationTokenHashByUserID(ctx context.Context, arg UpdateEmailVerificationTokenHashByUserIDParams) error {
	_, err := q.db.Exec(ctx, updateEmailVerificationTokenHashByUserID,
		arg.ID,
		arg.EmailVerificationTokenHash,
		arg.EmailVerificationTokenExpiresAt,
		arg.UpdatedAt,
	)
	return err
}

const updateLastLoginAtByUserID = `-- name: UpdateLastLoginAtByUserID :exec
UPDATE users SET
    last_login_at = $2,
    updated_at = $2
WHERE id = $1
`

type UpdateLastLoginAtByUserIDParams struct {
	ID          uuid.UUID
	LastLoginAt pgtype.Timestamptz
}

func (q *Queries) UpdateLastLoginAtByUserID(ctx context.Context, arg UpdateLastLoginAtByUserIDParams) error {
	_, err := q.db.Exec(ctx, updateLastLoginAtByUserID, arg.ID, arg.LastLoginAt)
	return err
}

const updateUserByID = `-- name: UpdateUserByID :exec
UPDATE users SET
    email = $2,
    first_name = $3,
    last_name = $4,
    username = $5,
    bio = $6,
    profile_picture = $7,
    location = $8,
    password_hash = $9,
    dob = $10,
    gender = $11,
    updated_at = $12,
    updated_by = $13
WHERE id = $1
`

type UpdateUserByIDParams struct {
	ID             uuid.UUID
	Email          string
	FirstName      string
	LastName       string
	Username       string
	Bio            pgtype.Text
	ProfilePicture pgtype.Text
	Location       pgtype.Text
	PasswordHash   string
	Dob            pgtype.Date
	Gender         Gender
	UpdatedAt      pgtype.Timestamptz
	UpdatedBy      pgtype.UUID
}

func (q *Queries) UpdateUserByID(ctx context.Context, arg UpdateUserByIDParams) error {
	_, err := q.db.Exec(ctx, updateUserByID,
		arg.ID,
		arg.Email,
		arg.FirstName,
		arg.LastName,
		arg.Username,
		arg.Bio,
		arg.ProfilePicture,
		arg.Location,
		arg.PasswordHash,
		arg.Dob,
		arg.Gender,
		arg.UpdatedAt,
		arg.UpdatedBy,
	)
	return err
}

const updateUserProfilePictureByID = `-- name: UpdateUserProfilePictureByID :exec
UPDATE users SET
    profile_picture = $2,
    updated_at = $3,
    updated_by = $1
WHERE id = $1
`

type UpdateUserProfilePictureByIDParams struct {
	UpdatedBy      pgtype.UUID
	ProfilePicture pgtype.Text
	UpdatedAt      pgtype.Timestamptz
}

func (q *Queries) UpdateUserProfilePictureByID(ctx context.Context, arg UpdateUserProfilePictureByIDParams) error {
	_, err := q.db.Exec(ctx, updateUserProfilePictureByID, arg.UpdatedBy, arg.ProfilePicture, arg.UpdatedAt)
	return err
}

const verifyUserEmailByTokenHash = `-- name: VerifyUserEmailByTokenHash :one
UPDATE users
SET
    email_verified = TRUE,
    email_verification_token_hash = NULL,
    email_verification_token_expires_at = NULL,
    updated_at = $2
WHERE
    email_verification_token_hash = $1
    AND email_verification_token_expires_at > NOW()
    AND email_verified = FALSE
RETURNING id
`

type VerifyUserEmailByTokenHashParams struct {
	EmailVerificationTokenHash []byte
	UpdatedAt                  pgtype.Timestamptz
}

func (q *Queries) VerifyUserEmailByTokenHash(ctx context.Context, arg VerifyUserEmailByTokenHashParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, verifyUserEmailByTokenHash, arg.EmailVerificationTokenHash, arg.UpdatedAt)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}
