INSERT INTO fighters (
    id,
    first_name,
    last_name,
    nickname,
    gender,
    dob,
    height,
    weight,
    reach,
    stance,
    country,
    fighting_out_of,
    bio,
    profile_picture,
    wins,
    losses,
    draws,
    disqualifications,
    no_contests,
    created_at,
    created_by,
    updated_at,
    updated_by
) VALUES
    (gen_random_uuid(), 'Conor', 'McGregor', 'The Notorious', 'male', '1988-07-14', 175.26, 70.31, 188.0, 'Southpaw', 'Ireland', 'Dublin, Ireland', 'Former UFC Featherweight and Lightweight Champion.', 'https://example.com/images/conor.jpg', 22, 6, 0, 0, 0, now(), 'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa', now(), 'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa'),
    (gen_random_uuid(), 'Khabib', 'Nurmagomedov', 'The Eagle', 'male', '1988-09-20', 177.8, 70.31, 178.0, 'Orthodox', 'Russia', 'Makhachkala, Russia', 'Retired undefeated former UFC Lightweight Champion.', 'https://example.com/images/khabib.jpg', 29, 0, 0, 0, 0, now(), 'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa', now(), 'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa'),
    (gen_random_uuid(), 'Israel', 'Adesanya', 'The Last Stylebender', 'male', '1989-07-22', 193.0, 83.9, 203.2, 'Switch', 'New Zealand', 'Auckland, New Zealand', 'Former UFC Middleweight Champion.', 'https://example.com/images/adesanya.jpg', 24, 3, 0, 0, 0, now(), 'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa', now(), 'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa'),
    (gen_random_uuid(), 'Amanda', 'Nunes', 'The Lioness', 'female', '1988-05-30', 173.0, 61.2, 175.3, 'Orthodox', 'Brazil', 'Miami, Florida, USA', 'Former UFC Bantamweight and Featherweight Champion.', 'https://example.com/images/nunes.jpg', 23, 5, 0, 0, 0, now(), 'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa', now(), 'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa'),
    (gen_random_uuid(), 'Jon', 'Jones', 'Bones', 'male', '1987-07-19', 193.0, 93.0, 215.9, 'Orthodox', 'USA', 'Albuquerque, New Mexico, USA', 'UFC Heavyweight and former Light Heavyweight Champion.', 'https://example.com/images/jones.jpg', 27, 1, 0, 1, 1, now(), 'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa', now(), 'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa');